/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  AccountsGetAccountsQueryData,
  buildAccountsGetAccountsQuery,
  prefetchAccountsGetAccounts,
  queryKeyAccountsGetAccounts,
} from "./accountsGetAccounts.core.js";
export {
  type AccountsGetAccountsQueryData,
  buildAccountsGetAccountsQuery,
  prefetchAccountsGetAccounts,
  queryKeyAccountsGetAccounts,
};

export type AccountsGetAccountsQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get all accounts
 *
 * @remarks
 * Returns all accounts
 */
export function useAccountsGetAccounts(
  request: operations.GetAccountsRequest,
  options?: QueryHookOptions<
    AccountsGetAccountsQueryData,
    AccountsGetAccountsQueryError
  >,
): UseQueryResult<AccountsGetAccountsQueryData, AccountsGetAccountsQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildAccountsGetAccountsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get all accounts
 *
 * @remarks
 * Returns all accounts
 */
export function useAccountsGetAccountsSuspense(
  request: operations.GetAccountsRequest,
  options?: SuspenseQueryHookOptions<
    AccountsGetAccountsQueryData,
    AccountsGetAccountsQueryError
  >,
): UseSuspenseQueryResult<
  AccountsGetAccountsQueryData,
  AccountsGetAccountsQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildAccountsGetAccountsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setAccountsGetAccountsData(
  client: QueryClient,
  queryKeyBase: [
    planId: string,
    parameters: { lastKnowledgeOfServer?: number | undefined },
  ],
  data: AccountsGetAccountsQueryData,
): AccountsGetAccountsQueryData | undefined {
  const key = queryKeyAccountsGetAccounts(...queryKeyBase);

  return client.setQueryData<AccountsGetAccountsQueryData>(key, data);
}

export function invalidateAccountsGetAccounts(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [planId: string, parameters: { lastKnowledgeOfServer?: number | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Accounts", "getAccounts", ...queryKeyBase],
  });
}

export function invalidateAllAccountsGetAccounts(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Accounts", "getAccounts"],
  });
}
