/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { accountsGetAccountById } from "../funcs/accountsGetAccountById.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type AccountsGetAccountByIdQueryData = models.AccountResponse;

export function prefetchAccountsGetAccountById(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetAccountByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAccountsGetAccountByIdQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildAccountsGetAccountByIdQuery(
  client$: YnabCore,
  request: operations.GetAccountByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AccountsGetAccountByIdQueryData>;
} {
  return {
    queryKey: queryKeyAccountsGetAccountById(request.planId, request.accountId),
    queryFn: async function accountsGetAccountByIdQueryFn(
      ctx,
    ): Promise<AccountsGetAccountByIdQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(accountsGetAccountById(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAccountsGetAccountById(
  planId: string,
  accountId: string,
): QueryKey {
  return ["ynab-ts", "Accounts", "getAccountById", planId, accountId];
}
