/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  AccountsGetAccountByIdQueryData,
  buildAccountsGetAccountByIdQuery,
  prefetchAccountsGetAccountById,
  queryKeyAccountsGetAccountById,
} from "./accountsGetAccountById.core.js";
export {
  type AccountsGetAccountByIdQueryData,
  buildAccountsGetAccountByIdQuery,
  prefetchAccountsGetAccountById,
  queryKeyAccountsGetAccountById,
};

export type AccountsGetAccountByIdQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get an account
 *
 * @remarks
 * Returns a single account
 */
export function useAccountsGetAccountById(
  request: operations.GetAccountByIdRequest,
  options?: QueryHookOptions<
    AccountsGetAccountByIdQueryData,
    AccountsGetAccountByIdQueryError
  >,
): UseQueryResult<
  AccountsGetAccountByIdQueryData,
  AccountsGetAccountByIdQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildAccountsGetAccountByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get an account
 *
 * @remarks
 * Returns a single account
 */
export function useAccountsGetAccountByIdSuspense(
  request: operations.GetAccountByIdRequest,
  options?: SuspenseQueryHookOptions<
    AccountsGetAccountByIdQueryData,
    AccountsGetAccountByIdQueryError
  >,
): UseSuspenseQueryResult<
  AccountsGetAccountByIdQueryData,
  AccountsGetAccountByIdQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildAccountsGetAccountByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setAccountsGetAccountByIdData(
  client: QueryClient,
  queryKeyBase: [planId: string, accountId: string],
  data: AccountsGetAccountByIdQueryData,
): AccountsGetAccountByIdQueryData | undefined {
  const key = queryKeyAccountsGetAccountById(...queryKeyBase);

  return client.setQueryData<AccountsGetAccountByIdQueryData>(key, data);
}

export function invalidateAccountsGetAccountById(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, accountId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Accounts", "getAccountById", ...queryKeyBase],
  });
}

export function invalidateAllAccountsGetAccountById(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Accounts", "getAccountById"],
  });
}
