/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { accountsGetAccounts } from "../funcs/accountsGetAccounts.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type AccountsGetAccountsQueryData = models.AccountsResponse;

export function prefetchAccountsGetAccounts(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetAccountsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAccountsGetAccountsQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildAccountsGetAccountsQuery(
  client$: YnabCore,
  request: operations.GetAccountsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AccountsGetAccountsQueryData>;
} {
  return {
    queryKey: queryKeyAccountsGetAccounts(request.planId, {
      lastKnowledgeOfServer: request.lastKnowledgeOfServer,
    }),
    queryFn: async function accountsGetAccountsQueryFn(
      ctx,
    ): Promise<AccountsGetAccountsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(accountsGetAccounts(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAccountsGetAccounts(
  planId: string,
  parameters: { lastKnowledgeOfServer?: number | undefined },
): QueryKey {
  return ["ynab-ts", "Accounts", "getAccounts", planId, parameters];
}
