/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { budgetsGetSettings } from "../funcs/budgetsGetSettings.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type BudgetsGetSettingsQueryData = models.BudgetSettingsResponse;

/**
 * Budget Settings
 *
 * @remarks
 * Returns settings for a budget
 */
export function useBudgetsGetSettings(
  request: operations.GetBudgetSettingsByIdRequest,
  options?: QueryHookOptions<BudgetsGetSettingsQueryData>,
): UseQueryResult<BudgetsGetSettingsQueryData, Error> {
  const client = useYnabContext();
  return useQuery({
    ...buildBudgetsGetSettingsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Budget Settings
 *
 * @remarks
 * Returns settings for a budget
 */
export function useBudgetsGetSettingsSuspense(
  request: operations.GetBudgetSettingsByIdRequest,
  options?: SuspenseQueryHookOptions<BudgetsGetSettingsQueryData>,
): UseSuspenseQueryResult<BudgetsGetSettingsQueryData, Error> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildBudgetsGetSettingsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchBudgetsGetSettings(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetBudgetSettingsByIdRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildBudgetsGetSettingsQuery(
      client$,
      request,
    ),
  });
}

export function setBudgetsGetSettingsData(
  client: QueryClient,
  queryKeyBase: [budgetId: string],
  data: BudgetsGetSettingsQueryData,
): BudgetsGetSettingsQueryData | undefined {
  const key = queryKeyBudgetsGetSettings(...queryKeyBase);

  return client.setQueryData<BudgetsGetSettingsQueryData>(key, data);
}

export function invalidateBudgetsGetSettings(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Budgets", "getSettings", ...queryKeyBase],
  });
}

export function invalidateAllBudgetsGetSettings(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Budgets", "getSettings"],
  });
}

export function buildBudgetsGetSettingsQuery(
  client$: YnabCore,
  request: operations.GetBudgetSettingsByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<BudgetsGetSettingsQueryData>;
} {
  return {
    queryKey: queryKeyBudgetsGetSettings(request.budgetId),
    queryFn: async function budgetsGetSettingsQueryFn(
      ctx,
    ): Promise<BudgetsGetSettingsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(budgetsGetSettings(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyBudgetsGetSettings(budgetId: string): QueryKey {
  return ["ynab-ts", "Budgets", "getSettings", budgetId];
}
