/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  BudgetsGetSettingsQueryData,
  buildBudgetsGetSettingsQuery,
  prefetchBudgetsGetSettings,
  queryKeyBudgetsGetSettings,
} from "./budgetsGetSettings.core.js";
export {
  type BudgetsGetSettingsQueryData,
  buildBudgetsGetSettingsQuery,
  prefetchBudgetsGetSettings,
  queryKeyBudgetsGetSettings,
};

export type BudgetsGetSettingsQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Budget Settings
 *
 * @remarks
 * Returns settings for a budget
 */
export function useBudgetsGetSettings(
  request: operations.GetBudgetSettingsByIdRequest,
  options?: QueryHookOptions<
    BudgetsGetSettingsQueryData,
    BudgetsGetSettingsQueryError
  >,
): UseQueryResult<BudgetsGetSettingsQueryData, BudgetsGetSettingsQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildBudgetsGetSettingsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Budget Settings
 *
 * @remarks
 * Returns settings for a budget
 */
export function useBudgetsGetSettingsSuspense(
  request: operations.GetBudgetSettingsByIdRequest,
  options?: SuspenseQueryHookOptions<
    BudgetsGetSettingsQueryData,
    BudgetsGetSettingsQueryError
  >,
): UseSuspenseQueryResult<
  BudgetsGetSettingsQueryData,
  BudgetsGetSettingsQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildBudgetsGetSettingsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setBudgetsGetSettingsData(
  client: QueryClient,
  queryKeyBase: [budgetId: string],
  data: BudgetsGetSettingsQueryData,
): BudgetsGetSettingsQueryData | undefined {
  const key = queryKeyBudgetsGetSettings(...queryKeyBase);

  return client.setQueryData<BudgetsGetSettingsQueryData>(key, data);
}

export function invalidateBudgetsGetSettings(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Budgets", "getSettings", ...queryKeyBase],
  });
}

export function invalidateAllBudgetsGetSettings(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Budgets", "getSettings"],
  });
}
