/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { budgetsList } from "../funcs/budgetsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type BudgetsListQueryData = models.BudgetSummaryResponse;

export function prefetchBudgetsList(
  queryClient: QueryClient,
  client$: YnabCore,
  request?: operations.GetBudgetsRequest | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildBudgetsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildBudgetsListQuery(
  client$: YnabCore,
  request?: operations.GetBudgetsRequest | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<BudgetsListQueryData>;
} {
  return {
    queryKey: queryKeyBudgetsList({
      includeAccounts: request?.includeAccounts,
    }),
    queryFn: async function budgetsListQueryFn(
      ctx,
    ): Promise<BudgetsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(budgetsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyBudgetsList(
  parameters: { includeAccounts?: boolean | undefined },
): QueryKey {
  return ["ynab-ts", "Budgets", "list", parameters];
}
