/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { budgetsGet } from "../funcs/budgetsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type BudgetsGetQueryData = models.BudgetDetailResponse;

export function prefetchBudgetsGet(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetBudgetByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildBudgetsGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildBudgetsGetQuery(
  client$: YnabCore,
  request: operations.GetBudgetByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<BudgetsGetQueryData>;
} {
  return {
    queryKey: queryKeyBudgetsGet(request.budgetId, {
      lastKnowledgeOfServer: request.lastKnowledgeOfServer,
    }),
    queryFn: async function budgetsGetQueryFn(
      ctx,
    ): Promise<BudgetsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(budgetsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyBudgetsGet(
  budgetId: string,
  parameters: { lastKnowledgeOfServer?: number | undefined },
): QueryKey {
  return ["ynab-ts", "Budgets", "get", budgetId, parameters];
}
