/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { categoriesGetByMonth } from "../funcs/categoriesGetByMonth.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type CategoriesGetByMonthQueryData = models.CategoryResponse;

export function prefetchCategoriesGetByMonth(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetMonthCategoryByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildCategoriesGetByMonthQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildCategoriesGetByMonthQuery(
  client$: YnabCore,
  request: operations.GetMonthCategoryByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<CategoriesGetByMonthQueryData>;
} {
  return {
    queryKey: queryKeyCategoriesGetByMonth(
      request.budgetId,
      request.month,
      request.categoryId,
    ),
    queryFn: async function categoriesGetByMonthQueryFn(
      ctx,
    ): Promise<CategoriesGetByMonthQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(categoriesGetByMonth(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyCategoriesGetByMonth(
  budgetId: string,
  month: RFCDate,
  categoryId: string,
): QueryKey {
  return ["ynab-ts", "Categories", "getByMonth", budgetId, month, categoryId];
}
