/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildCategoriesGetCategoryByIdQuery,
  CategoriesGetCategoryByIdQueryData,
  prefetchCategoriesGetCategoryById,
  queryKeyCategoriesGetCategoryById,
} from "./categoriesGetCategoryById.core.js";
export {
  buildCategoriesGetCategoryByIdQuery,
  type CategoriesGetCategoryByIdQueryData,
  prefetchCategoriesGetCategoryById,
  queryKeyCategoriesGetCategoryById,
};

export type CategoriesGetCategoryByIdQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a category
 *
 * @remarks
 * Returns a single category.  Amounts (assigned, activity, available, etc.) are specific to the current plan month (UTC).
 */
export function useCategoriesGetCategoryById(
  request: operations.GetCategoryByIdRequest,
  options?: QueryHookOptions<
    CategoriesGetCategoryByIdQueryData,
    CategoriesGetCategoryByIdQueryError
  >,
): UseQueryResult<
  CategoriesGetCategoryByIdQueryData,
  CategoriesGetCategoryByIdQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildCategoriesGetCategoryByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a category
 *
 * @remarks
 * Returns a single category.  Amounts (assigned, activity, available, etc.) are specific to the current plan month (UTC).
 */
export function useCategoriesGetCategoryByIdSuspense(
  request: operations.GetCategoryByIdRequest,
  options?: SuspenseQueryHookOptions<
    CategoriesGetCategoryByIdQueryData,
    CategoriesGetCategoryByIdQueryError
  >,
): UseSuspenseQueryResult<
  CategoriesGetCategoryByIdQueryData,
  CategoriesGetCategoryByIdQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildCategoriesGetCategoryByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setCategoriesGetCategoryByIdData(
  client: QueryClient,
  queryKeyBase: [planId: string, categoryId: string],
  data: CategoriesGetCategoryByIdQueryData,
): CategoriesGetCategoryByIdQueryData | undefined {
  const key = queryKeyCategoriesGetCategoryById(...queryKeyBase);

  return client.setQueryData<CategoriesGetCategoryByIdQueryData>(key, data);
}

export function invalidateCategoriesGetCategoryById(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, categoryId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Categories", "getCategoryById", ...queryKeyBase],
  });
}

export function invalidateAllCategoriesGetCategoryById(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Categories", "getCategoryById"],
  });
}
