/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { RFCDate } from "../types/rfcdate.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildCategoriesGetMonthCategoryByIdQuery,
  CategoriesGetMonthCategoryByIdQueryData,
  prefetchCategoriesGetMonthCategoryById,
  queryKeyCategoriesGetMonthCategoryById,
} from "./categoriesGetMonthCategoryById.core.js";
export {
  buildCategoriesGetMonthCategoryByIdQuery,
  type CategoriesGetMonthCategoryByIdQueryData,
  prefetchCategoriesGetMonthCategoryById,
  queryKeyCategoriesGetMonthCategoryById,
};

export type CategoriesGetMonthCategoryByIdQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a category for a specific plan month
 *
 * @remarks
 * Returns a single category for a specific plan month.  Amounts (assigned, activity, available, etc.) are specific to the current plan month (UTC).
 */
export function useCategoriesGetMonthCategoryById(
  request: operations.GetMonthCategoryByIdRequest,
  options?: QueryHookOptions<
    CategoriesGetMonthCategoryByIdQueryData,
    CategoriesGetMonthCategoryByIdQueryError
  >,
): UseQueryResult<
  CategoriesGetMonthCategoryByIdQueryData,
  CategoriesGetMonthCategoryByIdQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildCategoriesGetMonthCategoryByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a category for a specific plan month
 *
 * @remarks
 * Returns a single category for a specific plan month.  Amounts (assigned, activity, available, etc.) are specific to the current plan month (UTC).
 */
export function useCategoriesGetMonthCategoryByIdSuspense(
  request: operations.GetMonthCategoryByIdRequest,
  options?: SuspenseQueryHookOptions<
    CategoriesGetMonthCategoryByIdQueryData,
    CategoriesGetMonthCategoryByIdQueryError
  >,
): UseSuspenseQueryResult<
  CategoriesGetMonthCategoryByIdQueryData,
  CategoriesGetMonthCategoryByIdQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildCategoriesGetMonthCategoryByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setCategoriesGetMonthCategoryByIdData(
  client: QueryClient,
  queryKeyBase: [planId: string, month: RFCDate, categoryId: string],
  data: CategoriesGetMonthCategoryByIdQueryData,
): CategoriesGetMonthCategoryByIdQueryData | undefined {
  const key = queryKeyCategoriesGetMonthCategoryById(...queryKeyBase);

  return client.setQueryData<CategoriesGetMonthCategoryByIdQueryData>(
    key,
    data,
  );
}

export function invalidateCategoriesGetMonthCategoryById(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [planId: string, month: RFCDate, categoryId: string]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "ynab-ts",
      "Categories",
      "getMonthCategoryById",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllCategoriesGetMonthCategoryById(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Categories", "getMonthCategoryById"],
  });
}
