/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { categoriesCreateCategory } from "../funcs/categoriesCreateCategory.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CategoriesCreateCategoryMutationVariables = {
  request: operations.CreateCategoryRequest;
  options?: RequestOptions;
};

export type CategoriesCreateCategoryMutationData = models.SaveCategoryResponse;

export type CategoriesCreateCategoryMutationError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Create a category
 *
 * @remarks
 * Creates a new category
 */
export function useCategoriesCreateCategoryMutation(
  options?: MutationHookOptions<
    CategoriesCreateCategoryMutationData,
    CategoriesCreateCategoryMutationError,
    CategoriesCreateCategoryMutationVariables
  >,
): UseMutationResult<
  CategoriesCreateCategoryMutationData,
  CategoriesCreateCategoryMutationError,
  CategoriesCreateCategoryMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildCategoriesCreateCategoryMutation(client, options),
    ...options,
  });
}

export function mutationKeyCategoriesCreateCategory(): MutationKey {
  return ["ynab-ts", "Categories", "createCategory"];
}

export function buildCategoriesCreateCategoryMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CategoriesCreateCategoryMutationVariables,
  ) => Promise<CategoriesCreateCategoryMutationData>;
} {
  return {
    mutationKey: mutationKeyCategoriesCreateCategory(),
    mutationFn: function categoriesCreateCategoryMutationFn({
      request,
      options,
    }): Promise<CategoriesCreateCategoryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(categoriesCreateCategory(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
