/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { categoriesUpdate } from "../funcs/categoriesUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type CategoriesUpdateMutationVariables = {
  request: operations.UpdateCategoryRequest;
  options?: RequestOptions;
};

export type CategoriesUpdateMutationData = models.SaveCategoryResponse;

/**
 * Update a category
 *
 * @remarks
 * Update a category
 */
export function useCategoriesUpdateMutation(
  options?: MutationHookOptions<
    CategoriesUpdateMutationData,
    Error,
    CategoriesUpdateMutationVariables
  >,
): UseMutationResult<
  CategoriesUpdateMutationData,
  Error,
  CategoriesUpdateMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildCategoriesUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyCategoriesUpdate(): MutationKey {
  return ["ynab-ts", "Categories", "update"];
}

export function buildCategoriesUpdateMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: CategoriesUpdateMutationVariables,
  ) => Promise<CategoriesUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyCategoriesUpdate(),
    mutationFn: function categoriesUpdateMutationFn({
      request,
      options,
    }): Promise<CategoriesUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(categoriesUpdate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
