/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { RFCDate } from "../types/rfcdate.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildMoneyMovementsGetMoneyMovementGroupsByMonthQuery,
  MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
  prefetchMoneyMovementsGetMoneyMovementGroupsByMonth,
  queryKeyMoneyMovementsGetMoneyMovementGroupsByMonth,
} from "./moneyMovementsGetMoneyMovementGroupsByMonth.core.js";
export {
  buildMoneyMovementsGetMoneyMovementGroupsByMonthQuery,
  type MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
  prefetchMoneyMovementsGetMoneyMovementGroupsByMonth,
  queryKeyMoneyMovementsGetMoneyMovementGroupsByMonth,
};

export type MoneyMovementsGetMoneyMovementGroupsByMonthQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get money movement groups for a plan month
 *
 * @remarks
 * Returns all money movement groups for a specific month
 */
export function useMoneyMovementsGetMoneyMovementGroupsByMonth(
  request: operations.GetMoneyMovementGroupsByMonthRequest,
  options?: QueryHookOptions<
    MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
    MoneyMovementsGetMoneyMovementGroupsByMonthQueryError
  >,
): UseQueryResult<
  MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
  MoneyMovementsGetMoneyMovementGroupsByMonthQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildMoneyMovementsGetMoneyMovementGroupsByMonthQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get money movement groups for a plan month
 *
 * @remarks
 * Returns all money movement groups for a specific month
 */
export function useMoneyMovementsGetMoneyMovementGroupsByMonthSuspense(
  request: operations.GetMoneyMovementGroupsByMonthRequest,
  options?: SuspenseQueryHookOptions<
    MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
    MoneyMovementsGetMoneyMovementGroupsByMonthQueryError
  >,
): UseSuspenseQueryResult<
  MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
  MoneyMovementsGetMoneyMovementGroupsByMonthQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildMoneyMovementsGetMoneyMovementGroupsByMonthQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setMoneyMovementsGetMoneyMovementGroupsByMonthData(
  client: QueryClient,
  queryKeyBase: [planId: string, month: RFCDate],
  data: MoneyMovementsGetMoneyMovementGroupsByMonthQueryData,
): MoneyMovementsGetMoneyMovementGroupsByMonthQueryData | undefined {
  const key = queryKeyMoneyMovementsGetMoneyMovementGroupsByMonth(
    ...queryKeyBase,
  );

  return client.setQueryData<
    MoneyMovementsGetMoneyMovementGroupsByMonthQueryData
  >(key, data);
}

export function invalidateMoneyMovementsGetMoneyMovementGroupsByMonth(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, month: RFCDate]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "ynab-ts",
      "Money Movements",
      "getMoneyMovementGroupsByMonth",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllMoneyMovementsGetMoneyMovementGroupsByMonth(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Money Movements", "getMoneyMovementGroupsByMonth"],
  });
}
