/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { moneyMovementsGetMoneyMovementGroups } from "../funcs/moneyMovementsGetMoneyMovementGroups.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type MoneyMovementsGetMoneyMovementGroupsQueryData =
  models.MoneyMovementGroupsResponse;

export function prefetchMoneyMovementsGetMoneyMovementGroups(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetMoneyMovementGroupsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMoneyMovementsGetMoneyMovementGroupsQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildMoneyMovementsGetMoneyMovementGroupsQuery(
  client$: YnabCore,
  request: operations.GetMoneyMovementGroupsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<MoneyMovementsGetMoneyMovementGroupsQueryData>;
} {
  return {
    queryKey: queryKeyMoneyMovementsGetMoneyMovementGroups(request.planId),
    queryFn: async function moneyMovementsGetMoneyMovementGroupsQueryFn(
      ctx,
    ): Promise<MoneyMovementsGetMoneyMovementGroupsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(moneyMovementsGetMoneyMovementGroups(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMoneyMovementsGetMoneyMovementGroups(
  planId: string,
): QueryKey {
  return ["ynab-ts", "Money Movements", "getMoneyMovementGroups", planId];
}
