/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { moneyMovementsGetMoneyMovements } from "../funcs/moneyMovementsGetMoneyMovements.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type MoneyMovementsGetMoneyMovementsQueryData =
  models.MoneyMovementsResponse;

export function prefetchMoneyMovementsGetMoneyMovements(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetMoneyMovementsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMoneyMovementsGetMoneyMovementsQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildMoneyMovementsGetMoneyMovementsQuery(
  client$: YnabCore,
  request: operations.GetMoneyMovementsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<MoneyMovementsGetMoneyMovementsQueryData>;
} {
  return {
    queryKey: queryKeyMoneyMovementsGetMoneyMovements(request.planId),
    queryFn: async function moneyMovementsGetMoneyMovementsQueryFn(
      ctx,
    ): Promise<MoneyMovementsGetMoneyMovementsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(moneyMovementsGetMoneyMovements(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMoneyMovementsGetMoneyMovements(
  planId: string,
): QueryKey {
  return ["ynab-ts", "Money Movements", "getMoneyMovements", planId];
}
