/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { moneyMovementsGetMoneyMovementsByMonth } from "../funcs/moneyMovementsGetMoneyMovementsByMonth.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type MoneyMovementsGetMoneyMovementsByMonthQueryData =
  models.MoneyMovementsResponse;

export function prefetchMoneyMovementsGetMoneyMovementsByMonth(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetMoneyMovementsByMonthRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMoneyMovementsGetMoneyMovementsByMonthQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildMoneyMovementsGetMoneyMovementsByMonthQuery(
  client$: YnabCore,
  request: operations.GetMoneyMovementsByMonthRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<MoneyMovementsGetMoneyMovementsByMonthQueryData>;
} {
  return {
    queryKey: queryKeyMoneyMovementsGetMoneyMovementsByMonth(
      request.planId,
      request.month,
    ),
    queryFn: async function moneyMovementsGetMoneyMovementsByMonthQueryFn(
      ctx,
    ): Promise<MoneyMovementsGetMoneyMovementsByMonthQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(moneyMovementsGetMoneyMovementsByMonth(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMoneyMovementsGetMoneyMovementsByMonth(
  planId: string,
  month: RFCDate,
): QueryKey {
  return [
    "ynab-ts",
    "Money Movements",
    "getMoneyMovementsByMonth",
    planId,
    month,
  ];
}
