/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { RFCDate } from "../types/rfcdate.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildMonthsGetPlanMonthQuery,
  MonthsGetPlanMonthQueryData,
  prefetchMonthsGetPlanMonth,
  queryKeyMonthsGetPlanMonth,
} from "./monthsGetPlanMonth.core.js";
export {
  buildMonthsGetPlanMonthQuery,
  type MonthsGetPlanMonthQueryData,
  prefetchMonthsGetPlanMonth,
  queryKeyMonthsGetPlanMonth,
};

export type MonthsGetPlanMonthQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a plan month
 *
 * @remarks
 * Returns a single plan month
 */
export function useMonthsGetPlanMonth(
  request: operations.GetPlanMonthRequest,
  options?: QueryHookOptions<
    MonthsGetPlanMonthQueryData,
    MonthsGetPlanMonthQueryError
  >,
): UseQueryResult<MonthsGetPlanMonthQueryData, MonthsGetPlanMonthQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildMonthsGetPlanMonthQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a plan month
 *
 * @remarks
 * Returns a single plan month
 */
export function useMonthsGetPlanMonthSuspense(
  request: operations.GetPlanMonthRequest,
  options?: SuspenseQueryHookOptions<
    MonthsGetPlanMonthQueryData,
    MonthsGetPlanMonthQueryError
  >,
): UseSuspenseQueryResult<
  MonthsGetPlanMonthQueryData,
  MonthsGetPlanMonthQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildMonthsGetPlanMonthQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setMonthsGetPlanMonthData(
  client: QueryClient,
  queryKeyBase: [planId: string, month: RFCDate],
  data: MonthsGetPlanMonthQueryData,
): MonthsGetPlanMonthQueryData | undefined {
  const key = queryKeyMonthsGetPlanMonth(...queryKeyBase);

  return client.setQueryData<MonthsGetPlanMonthQueryData>(key, data);
}

export function invalidateMonthsGetPlanMonth(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, month: RFCDate]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Months", "getPlanMonth", ...queryKeyBase],
  });
}

export function invalidateAllMonthsGetPlanMonth(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Months", "getPlanMonth"],
  });
}
