/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { monthsGetPlanMonth } from "../funcs/monthsGetPlanMonth.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type MonthsGetPlanMonthQueryData = models.MonthDetailResponse;

export function prefetchMonthsGetPlanMonth(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPlanMonthRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMonthsGetPlanMonthQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildMonthsGetPlanMonthQuery(
  client$: YnabCore,
  request: operations.GetPlanMonthRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<MonthsGetPlanMonthQueryData>;
} {
  return {
    queryKey: queryKeyMonthsGetPlanMonth(request.planId, request.month),
    queryFn: async function monthsGetPlanMonthQueryFn(
      ctx,
    ): Promise<MonthsGetPlanMonthQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(monthsGetPlanMonth(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMonthsGetPlanMonth(
  planId: string,
  month: RFCDate,
): QueryKey {
  return ["ynab-ts", "Months", "getPlanMonth", planId, month];
}
