/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { monthsList } from "../funcs/monthsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type MonthsListQueryData = operations.GetBudgetMonthsResponse;

/**
 * List budget months
 *
 * @remarks
 * Returns all budget months
 */
export function useMonthsList(
  request: operations.GetBudgetMonthsRequest,
  options?: QueryHookOptions<MonthsListQueryData>,
): UseQueryResult<MonthsListQueryData, Error> {
  const client = useYnabContext();
  return useQuery({
    ...buildMonthsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List budget months
 *
 * @remarks
 * Returns all budget months
 */
export function useMonthsListSuspense(
  request: operations.GetBudgetMonthsRequest,
  options?: SuspenseQueryHookOptions<MonthsListQueryData>,
): UseSuspenseQueryResult<MonthsListQueryData, Error> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildMonthsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchMonthsList(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetBudgetMonthsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMonthsListQuery(
      client$,
      request,
    ),
  });
}

export function setMonthsListData(
  client: QueryClient,
  queryKeyBase: [
    budgetId: string,
    parameters: { lastKnowledgeOfServer?: number | undefined },
  ],
  data: MonthsListQueryData,
): MonthsListQueryData | undefined {
  const key = queryKeyMonthsList(...queryKeyBase);

  return client.setQueryData<MonthsListQueryData>(key, data);
}

export function invalidateMonthsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      budgetId: string,
      parameters: { lastKnowledgeOfServer?: number | undefined },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Months", "list", ...queryKeyBase],
  });
}

export function invalidateAllMonthsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Months", "list"],
  });
}

export function buildMonthsListQuery(
  client$: YnabCore,
  request: operations.GetBudgetMonthsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<MonthsListQueryData>;
} {
  return {
    queryKey: queryKeyMonthsList(request.budgetId, {
      lastKnowledgeOfServer: request.lastKnowledgeOfServer,
    }),
    queryFn: async function monthsListQueryFn(
      ctx,
    ): Promise<MonthsListQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(monthsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMonthsList(
  budgetId: string,
  parameters: { lastKnowledgeOfServer?: number | undefined },
): QueryKey {
  return ["ynab-ts", "Months", "list", budgetId, parameters];
}
