/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { monthsGet } from "../funcs/monthsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type MonthsGetQueryData = models.MonthDetailResponse;

export function prefetchMonthsGet(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetBudgetMonthRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildMonthsGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildMonthsGetQuery(
  client$: YnabCore,
  request: operations.GetBudgetMonthRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<MonthsGetQueryData>;
} {
  return {
    queryKey: queryKeyMonthsGet(request.budgetId, request.month),
    queryFn: async function monthsGetQueryFn(ctx): Promise<MonthsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(monthsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyMonthsGet(budgetId: string, month: RFCDate): QueryKey {
  return ["ynab-ts", "Months", "get", budgetId, month];
}
