/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPayeeLocationsListByPayeeQuery,
  PayeeLocationsListByPayeeQueryData,
  prefetchPayeeLocationsListByPayee,
  queryKeyPayeeLocationsListByPayee,
} from "./payeeLocationsListByPayee.core.js";
export {
  buildPayeeLocationsListByPayeeQuery,
  type PayeeLocationsListByPayeeQueryData,
  prefetchPayeeLocationsListByPayee,
  queryKeyPayeeLocationsListByPayee,
};

export type PayeeLocationsListByPayeeQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List locations for a payee
 *
 * @remarks
 * Returns all payee locations for a specified payee
 */
export function usePayeeLocationsListByPayee(
  request: operations.GetPayeeLocationsByPayeeRequest,
  options?: QueryHookOptions<
    PayeeLocationsListByPayeeQueryData,
    PayeeLocationsListByPayeeQueryError
  >,
): UseQueryResult<
  PayeeLocationsListByPayeeQueryData,
  PayeeLocationsListByPayeeQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildPayeeLocationsListByPayeeQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List locations for a payee
 *
 * @remarks
 * Returns all payee locations for a specified payee
 */
export function usePayeeLocationsListByPayeeSuspense(
  request: operations.GetPayeeLocationsByPayeeRequest,
  options?: SuspenseQueryHookOptions<
    PayeeLocationsListByPayeeQueryData,
    PayeeLocationsListByPayeeQueryError
  >,
): UseSuspenseQueryResult<
  PayeeLocationsListByPayeeQueryData,
  PayeeLocationsListByPayeeQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildPayeeLocationsListByPayeeQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPayeeLocationsListByPayeeData(
  client: QueryClient,
  queryKeyBase: [budgetId: string, payeeId: string],
  data: PayeeLocationsListByPayeeQueryData,
): PayeeLocationsListByPayeeQueryData | undefined {
  const key = queryKeyPayeeLocationsListByPayee(...queryKeyBase);

  return client.setQueryData<PayeeLocationsListByPayeeQueryData>(key, data);
}

export function invalidatePayeeLocationsListByPayee(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string, payeeId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "listByPayee", ...queryKeyBase],
  });
}

export function invalidateAllPayeeLocationsListByPayee(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "listByPayee"],
  });
}
