/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { payeesGet } from "../funcs/payeesGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type PayeesGetQueryData = models.PayeeResponse;

export function prefetchPayeesGet(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPayeeByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPayeesGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildPayeesGetQuery(
  client$: YnabCore,
  request: operations.GetPayeeByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<PayeesGetQueryData>;
} {
  return {
    queryKey: queryKeyPayeesGet(request.budgetId, request.payeeId),
    queryFn: async function payeesGetQueryFn(ctx): Promise<PayeesGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(payeesGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPayeesGet(budgetId: string, payeeId: string): QueryKey {
  return ["ynab-ts", "Payees", "get", budgetId, payeeId];
}
