/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { payeeLocationsGetPayeeLocations } from "../funcs/payeeLocationsGetPayeeLocations.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type PayeeLocationsGetPayeeLocationsQueryData =
  models.PayeeLocationsResponse;

export function prefetchPayeeLocationsGetPayeeLocations(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPayeeLocationsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPayeeLocationsGetPayeeLocationsQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildPayeeLocationsGetPayeeLocationsQuery(
  client$: YnabCore,
  request: operations.GetPayeeLocationsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PayeeLocationsGetPayeeLocationsQueryData>;
} {
  return {
    queryKey: queryKeyPayeeLocationsGetPayeeLocations(request.planId),
    queryFn: async function payeeLocationsGetPayeeLocationsQueryFn(
      ctx,
    ): Promise<PayeeLocationsGetPayeeLocationsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(payeeLocationsGetPayeeLocations(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPayeeLocationsGetPayeeLocations(
  planId: string,
): QueryKey {
  return ["ynab-ts", "Payee Locations", "getPayeeLocations", planId];
}
