/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { payeesUpdatePayee } from "../funcs/payeesUpdatePayee.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type PayeesUpdatePayeeMutationVariables = {
  request: operations.UpdatePayeeRequest;
  options?: RequestOptions;
};

export type PayeesUpdatePayeeMutationData = models.SavePayeeResponse;

export type PayeesUpdatePayeeMutationError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Update a payee
 *
 * @remarks
 * Update a payee
 */
export function usePayeesUpdatePayeeMutation(
  options?: MutationHookOptions<
    PayeesUpdatePayeeMutationData,
    PayeesUpdatePayeeMutationError,
    PayeesUpdatePayeeMutationVariables
  >,
): UseMutationResult<
  PayeesUpdatePayeeMutationData,
  PayeesUpdatePayeeMutationError,
  PayeesUpdatePayeeMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildPayeesUpdatePayeeMutation(client, options),
    ...options,
  });
}

export function mutationKeyPayeesUpdatePayee(): MutationKey {
  return ["ynab-ts", "Payees", "updatePayee"];
}

export function buildPayeesUpdatePayeeMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: PayeesUpdatePayeeMutationVariables,
  ) => Promise<PayeesUpdatePayeeMutationData>;
} {
  return {
    mutationKey: mutationKeyPayeesUpdatePayee(),
    mutationFn: function payeesUpdatePayeeMutationFn({
      request,
      options,
    }): Promise<PayeesUpdatePayeeMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(payeesUpdatePayee(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
