/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { payeeLocationsGet } from "../funcs/payeeLocationsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type PayeeLocationsGetQueryData =
  operations.GetPayeeLocationByIdResponse;

/**
 * Single payee location
 *
 * @remarks
 * Returns a single payee location
 */
export function usePayeeLocationsGet(
  request: operations.GetPayeeLocationByIdRequest,
  options?: QueryHookOptions<PayeeLocationsGetQueryData>,
): UseQueryResult<PayeeLocationsGetQueryData, Error> {
  const client = useYnabContext();
  return useQuery({
    ...buildPayeeLocationsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Single payee location
 *
 * @remarks
 * Returns a single payee location
 */
export function usePayeeLocationsGetSuspense(
  request: operations.GetPayeeLocationByIdRequest,
  options?: SuspenseQueryHookOptions<PayeeLocationsGetQueryData>,
): UseSuspenseQueryResult<PayeeLocationsGetQueryData, Error> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildPayeeLocationsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchPayeeLocationsGet(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPayeeLocationByIdRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPayeeLocationsGetQuery(
      client$,
      request,
    ),
  });
}

export function setPayeeLocationsGetData(
  client: QueryClient,
  queryKeyBase: [budgetId: string, payeeLocationId: string],
  data: PayeeLocationsGetQueryData,
): PayeeLocationsGetQueryData | undefined {
  const key = queryKeyPayeeLocationsGet(...queryKeyBase);

  return client.setQueryData<PayeeLocationsGetQueryData>(key, data);
}

export function invalidatePayeeLocationsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string, payeeLocationId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "get", ...queryKeyBase],
  });
}

export function invalidateAllPayeeLocationsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "get"],
  });
}

export function buildPayeeLocationsGetQuery(
  client$: YnabCore,
  request: operations.GetPayeeLocationByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PayeeLocationsGetQueryData>;
} {
  return {
    queryKey: queryKeyPayeeLocationsGet(
      request.budgetId,
      request.payeeLocationId,
    ),
    queryFn: async function payeeLocationsGetQueryFn(
      ctx,
    ): Promise<PayeeLocationsGetQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(payeeLocationsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPayeeLocationsGet(
  budgetId: string,
  payeeLocationId: string,
): QueryKey {
  return ["ynab-ts", "payeeLocations", "get", budgetId, payeeLocationId];
}
