/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { payeeLocationsList } from "../funcs/payeeLocationsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type PayeeLocationsListQueryData = operations.GetPayeeLocationsResponse;

/**
 * List payee locations
 *
 * @remarks
 * Returns all payee locations
 */
export function usePayeeLocationsList(
  request: operations.GetPayeeLocationsRequest,
  options?: QueryHookOptions<PayeeLocationsListQueryData>,
): UseQueryResult<PayeeLocationsListQueryData, Error> {
  const client = useYnabContext();
  return useQuery({
    ...buildPayeeLocationsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List payee locations
 *
 * @remarks
 * Returns all payee locations
 */
export function usePayeeLocationsListSuspense(
  request: operations.GetPayeeLocationsRequest,
  options?: SuspenseQueryHookOptions<PayeeLocationsListQueryData>,
): UseSuspenseQueryResult<PayeeLocationsListQueryData, Error> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildPayeeLocationsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchPayeeLocationsList(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPayeeLocationsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPayeeLocationsListQuery(
      client$,
      request,
    ),
  });
}

export function setPayeeLocationsListData(
  client: QueryClient,
  queryKeyBase: [budgetId: string],
  data: PayeeLocationsListQueryData,
): PayeeLocationsListQueryData | undefined {
  const key = queryKeyPayeeLocationsList(...queryKeyBase);

  return client.setQueryData<PayeeLocationsListQueryData>(key, data);
}

export function invalidatePayeeLocationsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "list", ...queryKeyBase],
  });
}

export function invalidateAllPayeeLocationsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "payeeLocations", "list"],
  });
}

export function buildPayeeLocationsListQuery(
  client$: YnabCore,
  request: operations.GetPayeeLocationsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PayeeLocationsListQueryData>;
} {
  return {
    queryKey: queryKeyPayeeLocationsList(request.budgetId),
    queryFn: async function payeeLocationsListQueryFn(
      ctx,
    ): Promise<PayeeLocationsListQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(payeeLocationsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPayeeLocationsList(budgetId: string): QueryKey {
  return ["ynab-ts", "payeeLocations", "list", budgetId];
}
