/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPayeesGetPayeeByIdQuery,
  PayeesGetPayeeByIdQueryData,
  prefetchPayeesGetPayeeById,
  queryKeyPayeesGetPayeeById,
} from "./payeesGetPayeeById.core.js";
export {
  buildPayeesGetPayeeByIdQuery,
  type PayeesGetPayeeByIdQueryData,
  prefetchPayeesGetPayeeById,
  queryKeyPayeesGetPayeeById,
};

export type PayeesGetPayeeByIdQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a payee
 *
 * @remarks
 * Returns a single payee
 */
export function usePayeesGetPayeeById(
  request: operations.GetPayeeByIdRequest,
  options?: QueryHookOptions<
    PayeesGetPayeeByIdQueryData,
    PayeesGetPayeeByIdQueryError
  >,
): UseQueryResult<PayeesGetPayeeByIdQueryData, PayeesGetPayeeByIdQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildPayeesGetPayeeByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a payee
 *
 * @remarks
 * Returns a single payee
 */
export function usePayeesGetPayeeByIdSuspense(
  request: operations.GetPayeeByIdRequest,
  options?: SuspenseQueryHookOptions<
    PayeesGetPayeeByIdQueryData,
    PayeesGetPayeeByIdQueryError
  >,
): UseSuspenseQueryResult<
  PayeesGetPayeeByIdQueryData,
  PayeesGetPayeeByIdQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildPayeesGetPayeeByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPayeesGetPayeeByIdData(
  client: QueryClient,
  queryKeyBase: [planId: string, payeeId: string],
  data: PayeesGetPayeeByIdQueryData,
): PayeesGetPayeeByIdQueryData | undefined {
  const key = queryKeyPayeesGetPayeeById(...queryKeyBase);

  return client.setQueryData<PayeesGetPayeeByIdQueryData>(key, data);
}

export function invalidatePayeesGetPayeeById(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, payeeId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Payees", "getPayeeById", ...queryKeyBase],
  });
}

export function invalidateAllPayeesGetPayeeById(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Payees", "getPayeeById"],
  });
}
