/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPayeesGetPayeesQuery,
  PayeesGetPayeesQueryData,
  prefetchPayeesGetPayees,
  queryKeyPayeesGetPayees,
} from "./payeesGetPayees.core.js";
export {
  buildPayeesGetPayeesQuery,
  type PayeesGetPayeesQueryData,
  prefetchPayeesGetPayees,
  queryKeyPayeesGetPayees,
};

export type PayeesGetPayeesQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get all payees
 *
 * @remarks
 * Returns all payees
 */
export function usePayeesGetPayees(
  request: operations.GetPayeesRequest,
  options?: QueryHookOptions<
    PayeesGetPayeesQueryData,
    PayeesGetPayeesQueryError
  >,
): UseQueryResult<PayeesGetPayeesQueryData, PayeesGetPayeesQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildPayeesGetPayeesQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get all payees
 *
 * @remarks
 * Returns all payees
 */
export function usePayeesGetPayeesSuspense(
  request: operations.GetPayeesRequest,
  options?: SuspenseQueryHookOptions<
    PayeesGetPayeesQueryData,
    PayeesGetPayeesQueryError
  >,
): UseSuspenseQueryResult<PayeesGetPayeesQueryData, PayeesGetPayeesQueryError> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildPayeesGetPayeesQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPayeesGetPayeesData(
  client: QueryClient,
  queryKeyBase: [
    planId: string,
    parameters: { lastKnowledgeOfServer?: number | undefined },
  ],
  data: PayeesGetPayeesQueryData,
): PayeesGetPayeesQueryData | undefined {
  const key = queryKeyPayeesGetPayees(...queryKeyBase);

  return client.setQueryData<PayeesGetPayeesQueryData>(key, data);
}

export function invalidatePayeesGetPayees(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [planId: string, parameters: { lastKnowledgeOfServer?: number | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Payees", "getPayees", ...queryKeyBase],
  });
}

export function invalidateAllPayeesGetPayees(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Payees", "getPayees"],
  });
}
