/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { plansGetPlanById } from "../funcs/plansGetPlanById.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type PlansGetPlanByIdQueryData = models.PlanDetailResponse;

export function prefetchPlansGetPlanById(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetPlanByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPlansGetPlanByIdQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildPlansGetPlanByIdQuery(
  client$: YnabCore,
  request: operations.GetPlanByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<PlansGetPlanByIdQueryData>;
} {
  return {
    queryKey: queryKeyPlansGetPlanById(request.planId, {
      lastKnowledgeOfServer: request.lastKnowledgeOfServer,
    }),
    queryFn: async function plansGetPlanByIdQueryFn(
      ctx,
    ): Promise<PlansGetPlanByIdQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(plansGetPlanById(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPlansGetPlanById(
  planId: string,
  parameters: { lastKnowledgeOfServer?: number | undefined },
): QueryKey {
  return ["ynab-ts", "Plans", "getPlanById", planId, parameters];
}
