/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { scheduledTransactionsGet } from "../funcs/scheduledTransactionsGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ScheduledTransactionsGetQueryData =
  models.ScheduledTransactionResponse;

export function prefetchScheduledTransactionsGet(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetScheduledTransactionByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildScheduledTransactionsGetQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildScheduledTransactionsGetQuery(
  client$: YnabCore,
  request: operations.GetScheduledTransactionByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ScheduledTransactionsGetQueryData>;
} {
  return {
    queryKey: queryKeyScheduledTransactionsGet(
      request.budgetId,
      request.scheduledTransactionId,
    ),
    queryFn: async function scheduledTransactionsGetQueryFn(
      ctx,
    ): Promise<ScheduledTransactionsGetQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(scheduledTransactionsGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyScheduledTransactionsGet(
  budgetId: string,
  scheduledTransactionId: string,
): QueryKey {
  return [
    "ynab-ts",
    "scheduledTransactions",
    "get",
    budgetId,
    scheduledTransactionId,
  ];
}
