/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { scheduledTransactionsUpdate } from "../funcs/scheduledTransactionsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ScheduledTransactionsUpdateMutationVariables = {
  request: operations.UpdateScheduledTransactionRequest;
  options?: RequestOptions;
};

export type ScheduledTransactionsUpdateMutationData =
  models.ScheduledTransactionResponse;

export type ScheduledTransactionsUpdateMutationError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Updates an existing scheduled transaction
 *
 * @remarks
 * Updates a single scheduled transaction
 */
export function useScheduledTransactionsUpdateMutation(
  options?: MutationHookOptions<
    ScheduledTransactionsUpdateMutationData,
    ScheduledTransactionsUpdateMutationError,
    ScheduledTransactionsUpdateMutationVariables
  >,
): UseMutationResult<
  ScheduledTransactionsUpdateMutationData,
  ScheduledTransactionsUpdateMutationError,
  ScheduledTransactionsUpdateMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildScheduledTransactionsUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyScheduledTransactionsUpdate(): MutationKey {
  return ["ynab-ts", "scheduledTransactions", "update"];
}

export function buildScheduledTransactionsUpdateMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ScheduledTransactionsUpdateMutationVariables,
  ) => Promise<ScheduledTransactionsUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyScheduledTransactionsUpdate(),
    mutationFn: function scheduledTransactionsUpdateMutationFn({
      request,
      options,
    }): Promise<ScheduledTransactionsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(scheduledTransactionsUpdate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
