/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { scheduledTransactionsList } from "../funcs/scheduledTransactionsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ScheduledTransactionsListQueryData =
  models.ScheduledTransactionsResponse;

export function prefetchScheduledTransactionsList(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetScheduledTransactionsRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildScheduledTransactionsListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildScheduledTransactionsListQuery(
  client$: YnabCore,
  request: operations.GetScheduledTransactionsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ScheduledTransactionsListQueryData>;
} {
  return {
    queryKey: queryKeyScheduledTransactionsList(request.budgetId, {
      lastKnowledgeOfServer: request.lastKnowledgeOfServer,
    }),
    queryFn: async function scheduledTransactionsListQueryFn(
      ctx,
    ): Promise<ScheduledTransactionsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(scheduledTransactionsList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyScheduledTransactionsList(
  budgetId: string,
  parameters: { lastKnowledgeOfServer?: number | undefined },
): QueryKey {
  return ["ynab-ts", "scheduledTransactions", "list", budgetId, parameters];
}
