/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildScheduledTransactionsGetQuery,
  prefetchScheduledTransactionsGet,
  queryKeyScheduledTransactionsGet,
  ScheduledTransactionsGetQueryData,
} from "./scheduledTransactionsGet.core.js";
export {
  buildScheduledTransactionsGetQuery,
  prefetchScheduledTransactionsGet,
  queryKeyScheduledTransactionsGet,
  type ScheduledTransactionsGetQueryData,
};

export type ScheduledTransactionsGetQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Single scheduled transaction
 *
 * @remarks
 * Returns a single scheduled transaction
 */
export function useScheduledTransactionsGet(
  request: operations.GetScheduledTransactionByIdRequest,
  options?: QueryHookOptions<
    ScheduledTransactionsGetQueryData,
    ScheduledTransactionsGetQueryError
  >,
): UseQueryResult<
  ScheduledTransactionsGetQueryData,
  ScheduledTransactionsGetQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildScheduledTransactionsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Single scheduled transaction
 *
 * @remarks
 * Returns a single scheduled transaction
 */
export function useScheduledTransactionsGetSuspense(
  request: operations.GetScheduledTransactionByIdRequest,
  options?: SuspenseQueryHookOptions<
    ScheduledTransactionsGetQueryData,
    ScheduledTransactionsGetQueryError
  >,
): UseSuspenseQueryResult<
  ScheduledTransactionsGetQueryData,
  ScheduledTransactionsGetQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildScheduledTransactionsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setScheduledTransactionsGetData(
  client: QueryClient,
  queryKeyBase: [budgetId: string, scheduledTransactionId: string],
  data: ScheduledTransactionsGetQueryData,
): ScheduledTransactionsGetQueryData | undefined {
  const key = queryKeyScheduledTransactionsGet(...queryKeyBase);

  return client.setQueryData<ScheduledTransactionsGetQueryData>(key, data);
}

export function invalidateScheduledTransactionsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [budgetId: string, scheduledTransactionId: string]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "scheduledTransactions", "get", ...queryKeyBase],
  });
}

export function invalidateAllScheduledTransactionsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "scheduledTransactions", "get"],
  });
}
