/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { transactionsGetTransactionsByAccount } from "../funcs/transactionsGetTransactionsByAccount.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type TransactionsGetTransactionsByAccountQueryData =
  models.TransactionsResponse;

export function prefetchTransactionsGetTransactionsByAccount(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetTransactionsByAccountRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildTransactionsGetTransactionsByAccountQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildTransactionsGetTransactionsByAccountQuery(
  client$: YnabCore,
  request: operations.GetTransactionsByAccountRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<TransactionsGetTransactionsByAccountQueryData>;
} {
  return {
    queryKey: queryKeyTransactionsGetTransactionsByAccount(
      request.planId,
      request.accountId,
      {
        sinceDate: request.sinceDate,
        untilDate: request.untilDate,
        type: request.type,
        lastKnowledgeOfServer: request.lastKnowledgeOfServer,
      },
    ),
    queryFn: async function transactionsGetTransactionsByAccountQueryFn(
      ctx,
    ): Promise<TransactionsGetTransactionsByAccountQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(transactionsGetTransactionsByAccount(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyTransactionsGetTransactionsByAccount(
  planId: string,
  accountId: string,
  parameters: {
    sinceDate?: RFCDate | undefined;
    untilDate?: RFCDate | undefined;
    type?: operations.GetTransactionsByAccountType | undefined;
    lastKnowledgeOfServer?: number | undefined;
  },
): QueryKey {
  return [
    "ynab-ts",
    "Transactions",
    "getTransactionsByAccount",
    planId,
    accountId,
    parameters,
  ];
}
