/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { transactionsCreate } from "../funcs/transactionsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TransactionsCreateMutationVariables = {
  request: operations.CreateTransactionRequest;
  options?: RequestOptions;
};

export type TransactionsCreateMutationData = models.SaveTransactionsResponse;

/**
 * Create a single transaction or multiple transactions
 *
 * @remarks
 * Creates a single transaction or multiple transactions.  If you provide a body containing a `transaction` object, a single transaction will be created and if you provide a body containing a `transactions` array, multiple transactions will be created.  Scheduled transactions (transactions with a future date) cannot be created on this endpoint.
 */
export function useTransactionsCreateMutation(
  options?: MutationHookOptions<
    TransactionsCreateMutationData,
    Error,
    TransactionsCreateMutationVariables
  >,
): UseMutationResult<
  TransactionsCreateMutationData,
  Error,
  TransactionsCreateMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildTransactionsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyTransactionsCreate(): MutationKey {
  return ["ynab-ts", "Transactions", "create"];
}

export function buildTransactionsCreateMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TransactionsCreateMutationVariables,
  ) => Promise<TransactionsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyTransactionsCreate(),
    mutationFn: function transactionsCreateMutationFn({
      request,
      options,
    }): Promise<TransactionsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(transactionsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
