/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransactionsGetQuery,
  prefetchTransactionsGet,
  queryKeyTransactionsGet,
  TransactionsGetQueryData,
} from "./transactionsGet.core.js";
export {
  buildTransactionsGetQuery,
  prefetchTransactionsGet,
  queryKeyTransactionsGet,
  type TransactionsGetQueryData,
};

export type TransactionsGetQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Single transaction
 *
 * @remarks
 * Returns a single transaction
 */
export function useTransactionsGet(
  request: operations.GetTransactionByIdRequest,
  options?: QueryHookOptions<
    TransactionsGetQueryData,
    TransactionsGetQueryError
  >,
): UseQueryResult<TransactionsGetQueryData, TransactionsGetQueryError> {
  const client = useYnabContext();
  return useQuery({
    ...buildTransactionsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Single transaction
 *
 * @remarks
 * Returns a single transaction
 */
export function useTransactionsGetSuspense(
  request: operations.GetTransactionByIdRequest,
  options?: SuspenseQueryHookOptions<
    TransactionsGetQueryData,
    TransactionsGetQueryError
  >,
): UseSuspenseQueryResult<TransactionsGetQueryData, TransactionsGetQueryError> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildTransactionsGetQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransactionsGetData(
  client: QueryClient,
  queryKeyBase: [budgetId: string, transactionId: string],
  data: TransactionsGetQueryData,
): TransactionsGetQueryData | undefined {
  const key = queryKeyTransactionsGet(...queryKeyBase);

  return client.setQueryData<TransactionsGetQueryData>(key, data);
}

export function invalidateTransactionsGet(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[budgetId: string, transactionId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "get", ...queryKeyBase],
  });
}

export function invalidateAllTransactionsGet(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "get"],
  });
}
