/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransactionsGetTransactionByIdQuery,
  prefetchTransactionsGetTransactionById,
  queryKeyTransactionsGetTransactionById,
  TransactionsGetTransactionByIdQueryData,
} from "./transactionsGetTransactionById.core.js";
export {
  buildTransactionsGetTransactionByIdQuery,
  prefetchTransactionsGetTransactionById,
  queryKeyTransactionsGetTransactionById,
  type TransactionsGetTransactionByIdQueryData,
};

export type TransactionsGetTransactionByIdQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get a transaction
 *
 * @remarks
 * Returns a single transaction
 */
export function useTransactionsGetTransactionById(
  request: operations.GetTransactionByIdRequest,
  options?: QueryHookOptions<
    TransactionsGetTransactionByIdQueryData,
    TransactionsGetTransactionByIdQueryError
  >,
): UseQueryResult<
  TransactionsGetTransactionByIdQueryData,
  TransactionsGetTransactionByIdQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildTransactionsGetTransactionByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a transaction
 *
 * @remarks
 * Returns a single transaction
 */
export function useTransactionsGetTransactionByIdSuspense(
  request: operations.GetTransactionByIdRequest,
  options?: SuspenseQueryHookOptions<
    TransactionsGetTransactionByIdQueryData,
    TransactionsGetTransactionByIdQueryError
  >,
): UseSuspenseQueryResult<
  TransactionsGetTransactionByIdQueryData,
  TransactionsGetTransactionByIdQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildTransactionsGetTransactionByIdQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransactionsGetTransactionByIdData(
  client: QueryClient,
  queryKeyBase: [planId: string, transactionId: string],
  data: TransactionsGetTransactionByIdQueryData,
): TransactionsGetTransactionByIdQueryData | undefined {
  const key = queryKeyTransactionsGetTransactionById(...queryKeyBase);

  return client.setQueryData<TransactionsGetTransactionByIdQueryData>(
    key,
    data,
  );
}

export function invalidateTransactionsGetTransactionById(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[planId: string, transactionId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "ynab-ts",
      "Transactions",
      "getTransactionById",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllTransactionsGetTransactionById(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "getTransactionById"],
  });
}
