/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { RFCDate } from "../types/rfcdate.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransactionsListByAccountQuery,
  prefetchTransactionsListByAccount,
  queryKeyTransactionsListByAccount,
  TransactionsListByAccountQueryData,
} from "./transactionsListByAccount.core.js";
export {
  buildTransactionsListByAccountQuery,
  prefetchTransactionsListByAccount,
  queryKeyTransactionsListByAccount,
  type TransactionsListByAccountQueryData,
};

export type TransactionsListByAccountQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List account transactions
 *
 * @remarks
 * Returns all transactions for a specified account, excluding any pending transactions
 */
export function useTransactionsListByAccount(
  request: operations.GetTransactionsByAccountRequest,
  options?: QueryHookOptions<
    TransactionsListByAccountQueryData,
    TransactionsListByAccountQueryError
  >,
): UseQueryResult<
  TransactionsListByAccountQueryData,
  TransactionsListByAccountQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildTransactionsListByAccountQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List account transactions
 *
 * @remarks
 * Returns all transactions for a specified account, excluding any pending transactions
 */
export function useTransactionsListByAccountSuspense(
  request: operations.GetTransactionsByAccountRequest,
  options?: SuspenseQueryHookOptions<
    TransactionsListByAccountQueryData,
    TransactionsListByAccountQueryError
  >,
): UseSuspenseQueryResult<
  TransactionsListByAccountQueryData,
  TransactionsListByAccountQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildTransactionsListByAccountQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransactionsListByAccountData(
  client: QueryClient,
  queryKeyBase: [
    budgetId: string,
    accountId: string,
    parameters: {
      sinceDate?: RFCDate | undefined;
      type?: operations.GetTransactionsByAccountType | undefined;
      lastKnowledgeOfServer?: number | undefined;
    },
  ],
  data: TransactionsListByAccountQueryData,
): TransactionsListByAccountQueryData | undefined {
  const key = queryKeyTransactionsListByAccount(...queryKeyBase);

  return client.setQueryData<TransactionsListByAccountQueryData>(key, data);
}

export function invalidateTransactionsListByAccount(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      budgetId: string,
      accountId: string,
      parameters: {
        sinceDate?: RFCDate | undefined;
        type?: operations.GetTransactionsByAccountType | undefined;
        lastKnowledgeOfServer?: number | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "listByAccount", ...queryKeyBase],
  });
}

export function invalidateAllTransactionsListByAccount(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "listByAccount"],
  });
}
