/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { transactionsDelete } from "../funcs/transactionsDelete.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useYnabContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TransactionsDeleteMutationVariables = {
  request: operations.DeleteTransactionRequest;
  options?: RequestOptions;
};

export type TransactionsDeleteMutationData = models.TransactionResponse;

export type TransactionsDeleteMutationError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Deletes an existing transaction
 *
 * @remarks
 * Deletes a transaction
 */
export function useTransactionsDeleteMutation(
  options?: MutationHookOptions<
    TransactionsDeleteMutationData,
    TransactionsDeleteMutationError,
    TransactionsDeleteMutationVariables
  >,
): UseMutationResult<
  TransactionsDeleteMutationData,
  TransactionsDeleteMutationError,
  TransactionsDeleteMutationVariables
> {
  const client = useYnabContext();
  return useMutation({
    ...buildTransactionsDeleteMutation(client, options),
    ...options,
  });
}

export function mutationKeyTransactionsDelete(): MutationKey {
  return ["ynab-ts", "Transactions", "delete"];
}

export function buildTransactionsDeleteMutation(
  client$: YnabCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: TransactionsDeleteMutationVariables,
  ) => Promise<TransactionsDeleteMutationData>;
} {
  return {
    mutationKey: mutationKeyTransactionsDelete(),
    mutationFn: function transactionsDeleteMutationFn({
      request,
      options,
    }): Promise<TransactionsDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(transactionsDelete(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
