/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { transactionsGetTransactionsByCategory } from "../funcs/transactionsGetTransactionsByCategory.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
export type TransactionsGetTransactionsByCategoryQueryData =
  models.HybridTransactionsResponse;

export function prefetchTransactionsGetTransactionsByCategory(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetTransactionsByCategoryRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildTransactionsGetTransactionsByCategoryQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildTransactionsGetTransactionsByCategoryQuery(
  client$: YnabCore,
  request: operations.GetTransactionsByCategoryRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<TransactionsGetTransactionsByCategoryQueryData>;
} {
  return {
    queryKey: queryKeyTransactionsGetTransactionsByCategory(
      request.planId,
      request.categoryId,
      {
        sinceDate: request.sinceDate,
        untilDate: request.untilDate,
        type: request.type,
        lastKnowledgeOfServer: request.lastKnowledgeOfServer,
      },
    ),
    queryFn: async function transactionsGetTransactionsByCategoryQueryFn(
      ctx,
    ): Promise<TransactionsGetTransactionsByCategoryQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(transactionsGetTransactionsByCategory(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyTransactionsGetTransactionsByCategory(
  planId: string,
  categoryId: string,
  parameters: {
    sinceDate?: RFCDate | undefined;
    untilDate?: RFCDate | undefined;
    type?: operations.GetTransactionsByCategoryType | undefined;
    lastKnowledgeOfServer?: number | undefined;
  },
): QueryKey {
  return [
    "ynab-ts",
    "Transactions",
    "getTransactionsByCategory",
    planId,
    categoryId,
    parameters,
  ];
}
