/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { YnabCore } from "../core.js";
import { transactionsGetTransactionById } from "../funcs/transactionsGetTransactionById.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type TransactionsGetTransactionByIdQueryData =
  models.TransactionResponse;

export function prefetchTransactionsGetTransactionById(
  queryClient: QueryClient,
  client$: YnabCore,
  request: operations.GetTransactionByIdRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildTransactionsGetTransactionByIdQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildTransactionsGetTransactionByIdQuery(
  client$: YnabCore,
  request: operations.GetTransactionByIdRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<TransactionsGetTransactionByIdQueryData>;
} {
  return {
    queryKey: queryKeyTransactionsGetTransactionById(
      request.planId,
      request.transactionId,
    ),
    queryFn: async function transactionsGetTransactionByIdQueryFn(
      ctx,
    ): Promise<TransactionsGetTransactionByIdQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(transactionsGetTransactionById(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyTransactionsGetTransactionById(
  planId: string,
  transactionId: string,
): QueryKey {
  return [
    "ynab-ts",
    "Transactions",
    "getTransactionById",
    planId,
    transactionId,
  ];
}
