/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { YnabError } from "../models/errors/ynaberror.js";
import * as operations from "../models/operations/index.js";
import { RFCDate } from "../types/rfcdate.js";
import { useYnabContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransactionsListByCategoryQuery,
  prefetchTransactionsListByCategory,
  queryKeyTransactionsListByCategory,
  TransactionsListByCategoryQueryData,
} from "./transactionsListByCategory.core.js";
export {
  buildTransactionsListByCategoryQuery,
  prefetchTransactionsListByCategory,
  queryKeyTransactionsListByCategory,
  type TransactionsListByCategoryQueryData,
};

export type TransactionsListByCategoryQueryError =
  | errors.ErrorResponse
  | YnabError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List category transactions, excluding any pending transactions
 *
 * @remarks
 * Returns all transactions for a specified category
 */
export function useTransactionsListByCategory(
  request: operations.GetTransactionsByCategoryRequest,
  options?: QueryHookOptions<
    TransactionsListByCategoryQueryData,
    TransactionsListByCategoryQueryError
  >,
): UseQueryResult<
  TransactionsListByCategoryQueryData,
  TransactionsListByCategoryQueryError
> {
  const client = useYnabContext();
  return useQuery({
    ...buildTransactionsListByCategoryQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List category transactions, excluding any pending transactions
 *
 * @remarks
 * Returns all transactions for a specified category
 */
export function useTransactionsListByCategorySuspense(
  request: operations.GetTransactionsByCategoryRequest,
  options?: SuspenseQueryHookOptions<
    TransactionsListByCategoryQueryData,
    TransactionsListByCategoryQueryError
  >,
): UseSuspenseQueryResult<
  TransactionsListByCategoryQueryData,
  TransactionsListByCategoryQueryError
> {
  const client = useYnabContext();
  return useSuspenseQuery({
    ...buildTransactionsListByCategoryQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransactionsListByCategoryData(
  client: QueryClient,
  queryKeyBase: [
    budgetId: string,
    categoryId: string,
    parameters: {
      sinceDate?: RFCDate | undefined;
      type?: operations.GetTransactionsByCategoryType | undefined;
      lastKnowledgeOfServer?: number | undefined;
    },
  ],
  data: TransactionsListByCategoryQueryData,
): TransactionsListByCategoryQueryData | undefined {
  const key = queryKeyTransactionsListByCategory(...queryKeyBase);

  return client.setQueryData<TransactionsListByCategoryQueryData>(key, data);
}

export function invalidateTransactionsListByCategory(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      budgetId: string,
      categoryId: string,
      parameters: {
        sinceDate?: RFCDate | undefined;
        type?: operations.GetTransactionsByCategoryType | undefined;
        lastKnowledgeOfServer?: number | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "listByCategory", ...queryKeyBase],
  });
}

export function invalidateAllTransactionsListByCategory(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["ynab-ts", "Transactions", "listByCategory"],
  });
}
