/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { moneyMovementsGetMoneyMovementGroups } from "../funcs/moneyMovementsGetMoneyMovementGroups.js";
import { moneyMovementsGetMoneyMovementGroupsByMonth } from "../funcs/moneyMovementsGetMoneyMovementGroupsByMonth.js";
import { moneyMovementsGetMoneyMovements } from "../funcs/moneyMovementsGetMoneyMovements.js";
import { moneyMovementsGetMoneyMovementsByMonth } from "../funcs/moneyMovementsGetMoneyMovementsByMonth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class MoneyMovements extends ClientSDK {
  /**
   * Get all money movements
   *
   * @remarks
   * Returns all money movements
   */
  async getMoneyMovements(
    request: operations.GetMoneyMovementsRequest,
    options?: RequestOptions,
  ): Promise<models.MoneyMovementsResponse> {
    return unwrapAsync(moneyMovementsGetMoneyMovements(
      this,
      request,
      options,
    ));
  }

  /**
   * Get money movements for a plan month
   *
   * @remarks
   * Returns all money movements for a specific month
   */
  async getMoneyMovementsByMonth(
    request: operations.GetMoneyMovementsByMonthRequest,
    options?: RequestOptions,
  ): Promise<models.MoneyMovementsResponse> {
    return unwrapAsync(moneyMovementsGetMoneyMovementsByMonth(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all money movement groups
   *
   * @remarks
   * Returns all money movement groups
   */
  async getMoneyMovementGroups(
    request: operations.GetMoneyMovementGroupsRequest,
    options?: RequestOptions,
  ): Promise<models.MoneyMovementGroupsResponse> {
    return unwrapAsync(moneyMovementsGetMoneyMovementGroups(
      this,
      request,
      options,
    ));
  }

  /**
   * Get money movement groups for a plan month
   *
   * @remarks
   * Returns all money movement groups for a specific month
   */
  async getMoneyMovementGroupsByMonth(
    request: operations.GetMoneyMovementGroupsByMonthRequest,
    options?: RequestOptions,
  ): Promise<models.MoneyMovementGroupsResponse> {
    return unwrapAsync(moneyMovementsGetMoneyMovementGroupsByMonth(
      this,
      request,
      options,
    ));
  }
}
