/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { monthsGetPlanMonth } from "../funcs/monthsGetPlanMonth.js";
import { monthsGetPlanMonths } from "../funcs/monthsGetPlanMonths.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Months extends ClientSDK {
  /**
   * Get all plan months
   *
   * @remarks
   * Returns all plan months
   */
  async getPlanMonths(
    request: operations.GetPlanMonthsRequest,
    options?: RequestOptions,
  ): Promise<models.MonthSummariesResponse> {
    return unwrapAsync(monthsGetPlanMonths(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a plan month
   *
   * @remarks
   * Returns a single plan month
   */
  async getPlanMonth(
    request: operations.GetPlanMonthRequest,
    options?: RequestOptions,
  ): Promise<models.MonthDetailResponse> {
    return unwrapAsync(monthsGetPlanMonth(
      this,
      request,
      options,
    ));
  }
}
