/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the ynab-ts SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx userGet.example.ts
 */

import { Ynab } from "ynab-ts";

const ynab = new Ynab({
  bearer: process.env["YNAB_BEARER"] ?? "",
});

async function main() {
  const result = await ynab.get();

  console.log(result);
}

main().catch(console.error);
