/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateCategoryGroupRequest = {
  /**
   * The id of the plan ("last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan)
   */
  planId: string;
  /**
   * The category group to create.
   */
  postCategoryGroupWrapper: models.PostCategoryGroupWrapper;
};

/** @internal */
export type CreateCategoryGroupRequest$Outbound = {
  plan_id: string;
  PostCategoryGroupWrapper: models.PostCategoryGroupWrapper$Outbound;
};

/** @internal */
export const CreateCategoryGroupRequest$outboundSchema: z.ZodType<
  CreateCategoryGroupRequest$Outbound,
  z.ZodTypeDef,
  CreateCategoryGroupRequest
> = z.object({
  planId: z.string(),
  postCategoryGroupWrapper: models.PostCategoryGroupWrapper$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    postCategoryGroupWrapper: "PostCategoryGroupWrapper",
  });
});

export function createCategoryGroupRequestToJSON(
  createCategoryGroupRequest: CreateCategoryGroupRequest,
): string {
  return JSON.stringify(
    CreateCategoryGroupRequest$outboundSchema.parse(createCategoryGroupRequest),
  );
}
