/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateAccountRequest = {
  /**
   * The id of the budget ("last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget)
   */
  budgetId: string;
  /**
   * The account to create.
   */
  postAccountWrapper: models.PostAccountWrapper;
};

/** @internal */
export const CreateAccountRequest$inboundSchema: z.ZodType<
  CreateAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  PostAccountWrapper: models.PostAccountWrapper$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "PostAccountWrapper": "postAccountWrapper",
  });
});

/** @internal */
export type CreateAccountRequest$Outbound = {
  budget_id: string;
  PostAccountWrapper: models.PostAccountWrapper$Outbound;
};

/** @internal */
export const CreateAccountRequest$outboundSchema: z.ZodType<
  CreateAccountRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountRequest
> = z.object({
  budgetId: z.string(),
  postAccountWrapper: models.PostAccountWrapper$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    postAccountWrapper: "PostAccountWrapper",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateAccountRequest$ {
  /** @deprecated use `CreateAccountRequest$inboundSchema` instead. */
  export const inboundSchema = CreateAccountRequest$inboundSchema;
  /** @deprecated use `CreateAccountRequest$outboundSchema` instead. */
  export const outboundSchema = CreateAccountRequest$outboundSchema;
  /** @deprecated use `CreateAccountRequest$Outbound` instead. */
  export type Outbound = CreateAccountRequest$Outbound;
}

export function createAccountRequestToJSON(
  createAccountRequest: CreateAccountRequest,
): string {
  return JSON.stringify(
    CreateAccountRequest$outboundSchema.parse(createAccountRequest),
  );
}

export function createAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountRequest' from JSON`,
  );
}
