/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateAccountRequest = {
  /**
   * The id of the plan ("last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan)
   */
  planId: string;
  /**
   * The account to create.
   */
  postAccountWrapper: models.PostAccountWrapper;
};

/** @internal */
export type CreateAccountRequest$Outbound = {
  plan_id: string;
  PostAccountWrapper: models.PostAccountWrapper$Outbound;
};

/** @internal */
export const CreateAccountRequest$outboundSchema: z.ZodType<
  CreateAccountRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountRequest
> = z.object({
  planId: z.string(),
  postAccountWrapper: models.PostAccountWrapper$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    postAccountWrapper: "PostAccountWrapper",
  });
});

export function createAccountRequestToJSON(
  createAccountRequest: CreateAccountRequest,
): string {
  return JSON.stringify(
    CreateAccountRequest$outboundSchema.parse(createAccountRequest),
  );
}
