/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteTransactionRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * The id of the transaction
   */
  transactionId: string;
};

/** @internal */
export type DeleteTransactionRequest$Outbound = {
  plan_id: string;
  transaction_id: string;
};

/** @internal */
export const DeleteTransactionRequest$outboundSchema: z.ZodType<
  DeleteTransactionRequest$Outbound,
  z.ZodTypeDef,
  DeleteTransactionRequest
> = z.object({
  planId: z.string(),
  transactionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    transactionId: "transaction_id",
  });
});

export function deleteTransactionRequestToJSON(
  deleteTransactionRequest: DeleteTransactionRequest,
): string {
  return JSON.stringify(
    DeleteTransactionRequest$outboundSchema.parse(deleteTransactionRequest),
  );
}
