/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteScheduledTransactionRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The id of the scheduled transaction
   */
  scheduledTransactionId: string;
};

/** @internal */
export const DeleteScheduledTransactionRequest$inboundSchema: z.ZodType<
  DeleteScheduledTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  scheduled_transaction_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "scheduled_transaction_id": "scheduledTransactionId",
  });
});

/** @internal */
export type DeleteScheduledTransactionRequest$Outbound = {
  budget_id: string;
  scheduled_transaction_id: string;
};

/** @internal */
export const DeleteScheduledTransactionRequest$outboundSchema: z.ZodType<
  DeleteScheduledTransactionRequest$Outbound,
  z.ZodTypeDef,
  DeleteScheduledTransactionRequest
> = z.object({
  budgetId: z.string(),
  scheduledTransactionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    scheduledTransactionId: "scheduled_transaction_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteScheduledTransactionRequest$ {
  /** @deprecated use `DeleteScheduledTransactionRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteScheduledTransactionRequest$inboundSchema;
  /** @deprecated use `DeleteScheduledTransactionRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteScheduledTransactionRequest$outboundSchema;
  /** @deprecated use `DeleteScheduledTransactionRequest$Outbound` instead. */
  export type Outbound = DeleteScheduledTransactionRequest$Outbound;
}

export function deleteScheduledTransactionRequestToJSON(
  deleteScheduledTransactionRequest: DeleteScheduledTransactionRequest,
): string {
  return JSON.stringify(
    DeleteScheduledTransactionRequest$outboundSchema.parse(
      deleteScheduledTransactionRequest,
    ),
  );
}

export function deleteScheduledTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteScheduledTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteScheduledTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteScheduledTransactionRequest' from JSON`,
  );
}
