/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteScheduledTransactionRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * The id of the scheduled transaction
   */
  scheduledTransactionId: string;
};

/** @internal */
export type DeleteScheduledTransactionRequest$Outbound = {
  plan_id: string;
  scheduled_transaction_id: string;
};

/** @internal */
export const DeleteScheduledTransactionRequest$outboundSchema: z.ZodType<
  DeleteScheduledTransactionRequest$Outbound,
  z.ZodTypeDef,
  DeleteScheduledTransactionRequest
> = z.object({
  planId: z.string(),
  scheduledTransactionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    scheduledTransactionId: "scheduled_transaction_id",
  });
});

export function deleteScheduledTransactionRequestToJSON(
  deleteScheduledTransactionRequest: DeleteScheduledTransactionRequest,
): string {
  return JSON.stringify(
    DeleteScheduledTransactionRequest$outboundSchema.parse(
      deleteScheduledTransactionRequest,
    ),
  );
}
