/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetAccountsRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

export type GetAccountsResponse =
  | models.AccountsResponse
  | models.ErrorResponse;

/** @internal */
export const GetAccountsRequest$inboundSchema: z.ZodType<
  GetAccountsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  last_knowledge_of_server: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "last_knowledge_of_server": "lastKnowledgeOfServer",
  });
});

/** @internal */
export type GetAccountsRequest$Outbound = {
  budget_id: string;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetAccountsRequest$outboundSchema: z.ZodType<
  GetAccountsRequest$Outbound,
  z.ZodTypeDef,
  GetAccountsRequest
> = z.object({
  budgetId: z.string(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAccountsRequest$ {
  /** @deprecated use `GetAccountsRequest$inboundSchema` instead. */
  export const inboundSchema = GetAccountsRequest$inboundSchema;
  /** @deprecated use `GetAccountsRequest$outboundSchema` instead. */
  export const outboundSchema = GetAccountsRequest$outboundSchema;
  /** @deprecated use `GetAccountsRequest$Outbound` instead. */
  export type Outbound = GetAccountsRequest$Outbound;
}

export function getAccountsRequestToJSON(
  getAccountsRequest: GetAccountsRequest,
): string {
  return JSON.stringify(
    GetAccountsRequest$outboundSchema.parse(getAccountsRequest),
  );
}

export function getAccountsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountsRequest' from JSON`,
  );
}

/** @internal */
export const GetAccountsResponse$inboundSchema: z.ZodType<
  GetAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.AccountsResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetAccountsResponse$Outbound =
  | models.AccountsResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const GetAccountsResponse$outboundSchema: z.ZodType<
  GetAccountsResponse$Outbound,
  z.ZodTypeDef,
  GetAccountsResponse
> = z.union([
  models.AccountsResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAccountsResponse$ {
  /** @deprecated use `GetAccountsResponse$inboundSchema` instead. */
  export const inboundSchema = GetAccountsResponse$inboundSchema;
  /** @deprecated use `GetAccountsResponse$outboundSchema` instead. */
  export const outboundSchema = GetAccountsResponse$outboundSchema;
  /** @deprecated use `GetAccountsResponse$Outbound` instead. */
  export type Outbound = GetAccountsResponse$Outbound;
}

export function getAccountsResponseToJSON(
  getAccountsResponse: GetAccountsResponse,
): string {
  return JSON.stringify(
    GetAccountsResponse$outboundSchema.parse(getAccountsResponse),
  );
}

export function getAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountsResponse' from JSON`,
  );
}
