/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetBudgetByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

/** @internal */
export type GetBudgetByIdRequest$Outbound = {
  budget_id: string;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetBudgetByIdRequest$outboundSchema: z.ZodType<
  GetBudgetByIdRequest$Outbound,
  z.ZodTypeDef,
  GetBudgetByIdRequest
> = z.object({
  budgetId: z.string(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

export function getBudgetByIdRequestToJSON(
  getBudgetByIdRequest: GetBudgetByIdRequest,
): string {
  return JSON.stringify(
    GetBudgetByIdRequest$outboundSchema.parse(getBudgetByIdRequest),
  );
}
