/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetBudgetSettingsByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
};

/** @internal */
export type GetBudgetSettingsByIdRequest$Outbound = {
  budget_id: string;
};

/** @internal */
export const GetBudgetSettingsByIdRequest$outboundSchema: z.ZodType<
  GetBudgetSettingsByIdRequest$Outbound,
  z.ZodTypeDef,
  GetBudgetSettingsByIdRequest
> = z.object({
  budgetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
  });
});

export function getBudgetSettingsByIdRequestToJSON(
  getBudgetSettingsByIdRequest: GetBudgetSettingsByIdRequest,
): string {
  return JSON.stringify(
    GetBudgetSettingsByIdRequest$outboundSchema.parse(
      getBudgetSettingsByIdRequest,
    ),
  );
}
