/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetBudgetByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

export type GetBudgetByIdResponse =
  | models.BudgetDetailResponse
  | models.ErrorResponse;

/** @internal */
export const GetBudgetByIdRequest$inboundSchema: z.ZodType<
  GetBudgetByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  last_knowledge_of_server: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "last_knowledge_of_server": "lastKnowledgeOfServer",
  });
});

/** @internal */
export type GetBudgetByIdRequest$Outbound = {
  budget_id: string;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetBudgetByIdRequest$outboundSchema: z.ZodType<
  GetBudgetByIdRequest$Outbound,
  z.ZodTypeDef,
  GetBudgetByIdRequest
> = z.object({
  budgetId: z.string(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBudgetByIdRequest$ {
  /** @deprecated use `GetBudgetByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetBudgetByIdRequest$inboundSchema;
  /** @deprecated use `GetBudgetByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetBudgetByIdRequest$outboundSchema;
  /** @deprecated use `GetBudgetByIdRequest$Outbound` instead. */
  export type Outbound = GetBudgetByIdRequest$Outbound;
}

export function getBudgetByIdRequestToJSON(
  getBudgetByIdRequest: GetBudgetByIdRequest,
): string {
  return JSON.stringify(
    GetBudgetByIdRequest$outboundSchema.parse(getBudgetByIdRequest),
  );
}

export function getBudgetByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetBudgetByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBudgetByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBudgetByIdRequest' from JSON`,
  );
}

/** @internal */
export const GetBudgetByIdResponse$inboundSchema: z.ZodType<
  GetBudgetByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.BudgetDetailResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetBudgetByIdResponse$Outbound =
  | models.BudgetDetailResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const GetBudgetByIdResponse$outboundSchema: z.ZodType<
  GetBudgetByIdResponse$Outbound,
  z.ZodTypeDef,
  GetBudgetByIdResponse
> = z.union([
  models.BudgetDetailResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBudgetByIdResponse$ {
  /** @deprecated use `GetBudgetByIdResponse$inboundSchema` instead. */
  export const inboundSchema = GetBudgetByIdResponse$inboundSchema;
  /** @deprecated use `GetBudgetByIdResponse$outboundSchema` instead. */
  export const outboundSchema = GetBudgetByIdResponse$outboundSchema;
  /** @deprecated use `GetBudgetByIdResponse$Outbound` instead. */
  export type Outbound = GetBudgetByIdResponse$Outbound;
}

export function getBudgetByIdResponseToJSON(
  getBudgetByIdResponse: GetBudgetByIdResponse,
): string {
  return JSON.stringify(
    GetBudgetByIdResponse$outboundSchema.parse(getBudgetByIdResponse),
  );
}

export function getBudgetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBudgetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBudgetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBudgetByIdResponse' from JSON`,
  );
}
