/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCategoriesRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

/** @internal */
export const GetCategoriesRequest$inboundSchema: z.ZodType<
  GetCategoriesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  last_knowledge_of_server: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "last_knowledge_of_server": "lastKnowledgeOfServer",
  });
});

/** @internal */
export type GetCategoriesRequest$Outbound = {
  budget_id: string;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetCategoriesRequest$outboundSchema: z.ZodType<
  GetCategoriesRequest$Outbound,
  z.ZodTypeDef,
  GetCategoriesRequest
> = z.object({
  budgetId: z.string(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCategoriesRequest$ {
  /** @deprecated use `GetCategoriesRequest$inboundSchema` instead. */
  export const inboundSchema = GetCategoriesRequest$inboundSchema;
  /** @deprecated use `GetCategoriesRequest$outboundSchema` instead. */
  export const outboundSchema = GetCategoriesRequest$outboundSchema;
  /** @deprecated use `GetCategoriesRequest$Outbound` instead. */
  export type Outbound = GetCategoriesRequest$Outbound;
}

export function getCategoriesRequestToJSON(
  getCategoriesRequest: GetCategoriesRequest,
): string {
  return JSON.stringify(
    GetCategoriesRequest$outboundSchema.parse(getCategoriesRequest),
  );
}

export function getCategoriesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCategoriesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCategoriesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCategoriesRequest' from JSON`,
  );
}
