/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetMoneyMovementsRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
};

/** @internal */
export type GetMoneyMovementsRequest$Outbound = {
  plan_id: string;
};

/** @internal */
export const GetMoneyMovementsRequest$outboundSchema: z.ZodType<
  GetMoneyMovementsRequest$Outbound,
  z.ZodTypeDef,
  GetMoneyMovementsRequest
> = z.object({
  planId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
  });
});

export function getMoneyMovementsRequestToJSON(
  getMoneyMovementsRequest: GetMoneyMovementsRequest,
): string {
  return JSON.stringify(
    GetMoneyMovementsRequest$outboundSchema.parse(getMoneyMovementsRequest),
  );
}
