/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { RFCDate } from "../../types/rfcdate.js";

export type GetMonthCategoryByIdRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * The plan month in ISO format (e.g. 2016-12-01) ("current" can also be used to specify the current calendar month (UTC))
   */
  month: RFCDate;
  /**
   * The id of the category
   */
  categoryId: string;
};

/** @internal */
export type GetMonthCategoryByIdRequest$Outbound = {
  plan_id: string;
  month: string;
  category_id: string;
};

/** @internal */
export const GetMonthCategoryByIdRequest$outboundSchema: z.ZodType<
  GetMonthCategoryByIdRequest$Outbound,
  z.ZodTypeDef,
  GetMonthCategoryByIdRequest
> = z.object({
  planId: z.string(),
  month: z.instanceof(RFCDate).transform(v => v.toString()),
  categoryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    categoryId: "category_id",
  });
});

export function getMonthCategoryByIdRequestToJSON(
  getMonthCategoryByIdRequest: GetMonthCategoryByIdRequest,
): string {
  return JSON.stringify(
    GetMonthCategoryByIdRequest$outboundSchema.parse(
      getMonthCategoryByIdRequest,
    ),
  );
}
