/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMonthCategoryByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The budget month in ISO format (e.g. 2016-12-01) ("current" can also be used to specify the current calendar month (UTC))
   */
  month: RFCDate;
  /**
   * The id of the category
   */
  categoryId: string;
};

/** @internal */
export const GetMonthCategoryByIdRequest$inboundSchema: z.ZodType<
  GetMonthCategoryByIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  month: z.string().transform(v => new RFCDate(v)),
  category_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "category_id": "categoryId",
  });
});

/** @internal */
export type GetMonthCategoryByIdRequest$Outbound = {
  budget_id: string;
  month: string;
  category_id: string;
};

/** @internal */
export const GetMonthCategoryByIdRequest$outboundSchema: z.ZodType<
  GetMonthCategoryByIdRequest$Outbound,
  z.ZodTypeDef,
  GetMonthCategoryByIdRequest
> = z.object({
  budgetId: z.string(),
  month: z.instanceof(RFCDate).transform(v => v.toString()),
  categoryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    categoryId: "category_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMonthCategoryByIdRequest$ {
  /** @deprecated use `GetMonthCategoryByIdRequest$inboundSchema` instead. */
  export const inboundSchema = GetMonthCategoryByIdRequest$inboundSchema;
  /** @deprecated use `GetMonthCategoryByIdRequest$outboundSchema` instead. */
  export const outboundSchema = GetMonthCategoryByIdRequest$outboundSchema;
  /** @deprecated use `GetMonthCategoryByIdRequest$Outbound` instead. */
  export type Outbound = GetMonthCategoryByIdRequest$Outbound;
}

export function getMonthCategoryByIdRequestToJSON(
  getMonthCategoryByIdRequest: GetMonthCategoryByIdRequest,
): string {
  return JSON.stringify(
    GetMonthCategoryByIdRequest$outboundSchema.parse(
      getMonthCategoryByIdRequest,
    ),
  );
}

export function getMonthCategoryByIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMonthCategoryByIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMonthCategoryByIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMonthCategoryByIdRequest' from JSON`,
  );
}
