/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPlansRequest = {
  /**
   * Whether to include the list of plan accounts
   */
  includeAccounts?: boolean | undefined;
};

/** @internal */
export type GetPlansRequest$Outbound = {
  include_accounts?: boolean | undefined;
};

/** @internal */
export const GetPlansRequest$outboundSchema: z.ZodType<
  GetPlansRequest$Outbound,
  z.ZodTypeDef,
  GetPlansRequest
> = z.object({
  includeAccounts: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    includeAccounts: "include_accounts",
  });
});

export function getPlansRequestToJSON(
  getPlansRequest: GetPlansRequest,
): string {
  return JSON.stringify(GetPlansRequest$outboundSchema.parse(getPlansRequest));
}
