/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPayeeLocationsByPayeeRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * id of payee
   */
  payeeId: string;
};

/** @internal */
export type GetPayeeLocationsByPayeeRequest$Outbound = {
  plan_id: string;
  payee_id: string;
};

/** @internal */
export const GetPayeeLocationsByPayeeRequest$outboundSchema: z.ZodType<
  GetPayeeLocationsByPayeeRequest$Outbound,
  z.ZodTypeDef,
  GetPayeeLocationsByPayeeRequest
> = z.object({
  planId: z.string(),
  payeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    payeeId: "payee_id",
  });
});

export function getPayeeLocationsByPayeeRequestToJSON(
  getPayeeLocationsByPayeeRequest: GetPayeeLocationsByPayeeRequest,
): string {
  return JSON.stringify(
    GetPayeeLocationsByPayeeRequest$outboundSchema.parse(
      getPayeeLocationsByPayeeRequest,
    ),
  );
}
