/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetPayeeLocationsByPayeeRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * id of payee
   */
  payeeId: string;
};

export type GetPayeeLocationsByPayeeResponse =
  | models.PayeeLocationsResponse
  | models.ErrorResponse;

/** @internal */
export const GetPayeeLocationsByPayeeRequest$inboundSchema: z.ZodType<
  GetPayeeLocationsByPayeeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  payee_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "payee_id": "payeeId",
  });
});

/** @internal */
export type GetPayeeLocationsByPayeeRequest$Outbound = {
  budget_id: string;
  payee_id: string;
};

/** @internal */
export const GetPayeeLocationsByPayeeRequest$outboundSchema: z.ZodType<
  GetPayeeLocationsByPayeeRequest$Outbound,
  z.ZodTypeDef,
  GetPayeeLocationsByPayeeRequest
> = z.object({
  budgetId: z.string(),
  payeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    payeeId: "payee_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPayeeLocationsByPayeeRequest$ {
  /** @deprecated use `GetPayeeLocationsByPayeeRequest$inboundSchema` instead. */
  export const inboundSchema = GetPayeeLocationsByPayeeRequest$inboundSchema;
  /** @deprecated use `GetPayeeLocationsByPayeeRequest$outboundSchema` instead. */
  export const outboundSchema = GetPayeeLocationsByPayeeRequest$outboundSchema;
  /** @deprecated use `GetPayeeLocationsByPayeeRequest$Outbound` instead. */
  export type Outbound = GetPayeeLocationsByPayeeRequest$Outbound;
}

export function getPayeeLocationsByPayeeRequestToJSON(
  getPayeeLocationsByPayeeRequest: GetPayeeLocationsByPayeeRequest,
): string {
  return JSON.stringify(
    GetPayeeLocationsByPayeeRequest$outboundSchema.parse(
      getPayeeLocationsByPayeeRequest,
    ),
  );
}

export function getPayeeLocationsByPayeeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPayeeLocationsByPayeeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPayeeLocationsByPayeeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPayeeLocationsByPayeeRequest' from JSON`,
  );
}

/** @internal */
export const GetPayeeLocationsByPayeeResponse$inboundSchema: z.ZodType<
  GetPayeeLocationsByPayeeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.PayeeLocationsResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetPayeeLocationsByPayeeResponse$Outbound =
  | models.PayeeLocationsResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const GetPayeeLocationsByPayeeResponse$outboundSchema: z.ZodType<
  GetPayeeLocationsByPayeeResponse$Outbound,
  z.ZodTypeDef,
  GetPayeeLocationsByPayeeResponse
> = z.union([
  models.PayeeLocationsResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPayeeLocationsByPayeeResponse$ {
  /** @deprecated use `GetPayeeLocationsByPayeeResponse$inboundSchema` instead. */
  export const inboundSchema = GetPayeeLocationsByPayeeResponse$inboundSchema;
  /** @deprecated use `GetPayeeLocationsByPayeeResponse$outboundSchema` instead. */
  export const outboundSchema = GetPayeeLocationsByPayeeResponse$outboundSchema;
  /** @deprecated use `GetPayeeLocationsByPayeeResponse$Outbound` instead. */
  export type Outbound = GetPayeeLocationsByPayeeResponse$Outbound;
}

export function getPayeeLocationsByPayeeResponseToJSON(
  getPayeeLocationsByPayeeResponse: GetPayeeLocationsByPayeeResponse,
): string {
  return JSON.stringify(
    GetPayeeLocationsByPayeeResponse$outboundSchema.parse(
      getPayeeLocationsByPayeeResponse,
    ),
  );
}

export function getPayeeLocationsByPayeeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPayeeLocationsByPayeeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPayeeLocationsByPayeeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPayeeLocationsByPayeeResponse' from JSON`,
  );
}
