/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPayeeLocationByIdRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * id of payee location
   */
  payeeLocationId: string;
};

/** @internal */
export type GetPayeeLocationByIdRequest$Outbound = {
  plan_id: string;
  payee_location_id: string;
};

/** @internal */
export const GetPayeeLocationByIdRequest$outboundSchema: z.ZodType<
  GetPayeeLocationByIdRequest$Outbound,
  z.ZodTypeDef,
  GetPayeeLocationByIdRequest
> = z.object({
  planId: z.string(),
  payeeLocationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    payeeLocationId: "payee_location_id",
  });
});

export function getPayeeLocationByIdRequestToJSON(
  getPayeeLocationByIdRequest: GetPayeeLocationByIdRequest,
): string {
  return JSON.stringify(
    GetPayeeLocationByIdRequest$outboundSchema.parse(
      getPayeeLocationByIdRequest,
    ),
  );
}
