/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPlanSettingsByIdRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
};

/** @internal */
export type GetPlanSettingsByIdRequest$Outbound = {
  plan_id: string;
};

/** @internal */
export const GetPlanSettingsByIdRequest$outboundSchema: z.ZodType<
  GetPlanSettingsByIdRequest$Outbound,
  z.ZodTypeDef,
  GetPlanSettingsByIdRequest
> = z.object({
  planId: z.string(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
  });
});

export function getPlanSettingsByIdRequestToJSON(
  getPlanSettingsByIdRequest: GetPlanSettingsByIdRequest,
): string {
  return JSON.stringify(
    GetPlanSettingsByIdRequest$outboundSchema.parse(getPlanSettingsByIdRequest),
  );
}
