/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPayeeByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The id of the payee
   */
  payeeId: string;
};

/** @internal */
export type GetPayeeByIdRequest$Outbound = {
  budget_id: string;
  payee_id: string;
};

/** @internal */
export const GetPayeeByIdRequest$outboundSchema: z.ZodType<
  GetPayeeByIdRequest$Outbound,
  z.ZodTypeDef,
  GetPayeeByIdRequest
> = z.object({
  budgetId: z.string(),
  payeeId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    payeeId: "payee_id",
  });
});

export function getPayeeByIdRequestToJSON(
  getPayeeByIdRequest: GetPayeeByIdRequest,
): string {
  return JSON.stringify(
    GetPayeeByIdRequest$outboundSchema.parse(getPayeeByIdRequest),
  );
}
