/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetPayeesRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

/** @internal */
export type GetPayeesRequest$Outbound = {
  plan_id: string;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetPayeesRequest$outboundSchema: z.ZodType<
  GetPayeesRequest$Outbound,
  z.ZodTypeDef,
  GetPayeesRequest
> = z.object({
  planId: z.string(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

export function getPayeesRequestToJSON(
  getPayeesRequest: GetPayeesRequest,
): string {
  return JSON.stringify(
    GetPayeesRequest$outboundSchema.parse(getPayeesRequest),
  );
}
