/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetScheduledTransactionByIdRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The id of the scheduled transaction
   */
  scheduledTransactionId: string;
};

/** @internal */
export type GetScheduledTransactionByIdRequest$Outbound = {
  budget_id: string;
  scheduled_transaction_id: string;
};

/** @internal */
export const GetScheduledTransactionByIdRequest$outboundSchema: z.ZodType<
  GetScheduledTransactionByIdRequest$Outbound,
  z.ZodTypeDef,
  GetScheduledTransactionByIdRequest
> = z.object({
  budgetId: z.string(),
  scheduledTransactionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    scheduledTransactionId: "scheduled_transaction_id",
  });
});

export function getScheduledTransactionByIdRequestToJSON(
  getScheduledTransactionByIdRequest: GetScheduledTransactionByIdRequest,
): string {
  return JSON.stringify(
    GetScheduledTransactionByIdRequest$outboundSchema.parse(
      getScheduledTransactionByIdRequest,
    ),
  );
}
