/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { RFCDate } from "../../types/rfcdate.js";

/**
 * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
 */
export const GetTransactionsByCategoryType = {
  Uncategorized: "uncategorized",
  Unapproved: "unapproved",
} as const;
/**
 * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
 */
export type GetTransactionsByCategoryType = ClosedEnum<
  typeof GetTransactionsByCategoryType
>;

export type GetTransactionsByCategoryRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The id of the category
   */
  categoryId: string;
  /**
   * If specified, only transactions on or after this date will be included.  The date should be ISO formatted (e.g. 2016-12-30).
   */
  sinceDate?: RFCDate | undefined;
  /**
   * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
   */
  type?: GetTransactionsByCategoryType | undefined;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

/** @internal */
export const GetTransactionsByCategoryType$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsByCategoryType
> = z.nativeEnum(GetTransactionsByCategoryType);

/** @internal */
export type GetTransactionsByCategoryRequest$Outbound = {
  budget_id: string;
  category_id: string;
  since_date?: string | undefined;
  type?: string | undefined;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetTransactionsByCategoryRequest$outboundSchema: z.ZodType<
  GetTransactionsByCategoryRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsByCategoryRequest
> = z.object({
  budgetId: z.string(),
  categoryId: z.string(),
  sinceDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  type: GetTransactionsByCategoryType$outboundSchema.optional(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    categoryId: "category_id",
    sinceDate: "since_date",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

export function getTransactionsByCategoryRequestToJSON(
  getTransactionsByCategoryRequest: GetTransactionsByCategoryRequest,
): string {
  return JSON.stringify(
    GetTransactionsByCategoryRequest$outboundSchema.parse(
      getTransactionsByCategoryRequest,
    ),
  );
}
