/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
 */
export const GetTransactionsByMonthType = {
  Uncategorized: "uncategorized",
  Unapproved: "unapproved",
} as const;
/**
 * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
 */
export type GetTransactionsByMonthType = ClosedEnum<
  typeof GetTransactionsByMonthType
>;

export type GetTransactionsByMonthRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
  /**
   * The budget month in ISO format (e.g. 2016-12-01) ("current" can also be used to specify the current calendar month (UTC))
   */
  month: string;
  /**
   * If specified, only transactions on or after this date will be included.  The date should be ISO formatted (e.g. 2016-12-30).
   */
  sinceDate?: RFCDate | undefined;
  /**
   * If specified, only transactions of the specified type will be included. "uncategorized" and "unapproved" are currently supported.
   */
  type?: GetTransactionsByMonthType | undefined;
  /**
   * The starting server knowledge.  If provided, only entities that have changed since `last_knowledge_of_server` will be included.
   */
  lastKnowledgeOfServer?: number | undefined;
};

/** @internal */
export const GetTransactionsByMonthType$inboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsByMonthType
> = z.nativeEnum(GetTransactionsByMonthType);

/** @internal */
export const GetTransactionsByMonthType$outboundSchema: z.ZodNativeEnum<
  typeof GetTransactionsByMonthType
> = GetTransactionsByMonthType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsByMonthType$ {
  /** @deprecated use `GetTransactionsByMonthType$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsByMonthType$inboundSchema;
  /** @deprecated use `GetTransactionsByMonthType$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsByMonthType$outboundSchema;
}

/** @internal */
export const GetTransactionsByMonthRequest$inboundSchema: z.ZodType<
  GetTransactionsByMonthRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget_id: z.string(),
  month: z.string(),
  since_date: z.string().transform(v => new RFCDate(v)).optional(),
  type: GetTransactionsByMonthType$inboundSchema.optional(),
  last_knowledge_of_server: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "budget_id": "budgetId",
    "since_date": "sinceDate",
    "last_knowledge_of_server": "lastKnowledgeOfServer",
  });
});

/** @internal */
export type GetTransactionsByMonthRequest$Outbound = {
  budget_id: string;
  month: string;
  since_date?: string | undefined;
  type?: string | undefined;
  last_knowledge_of_server?: number | undefined;
};

/** @internal */
export const GetTransactionsByMonthRequest$outboundSchema: z.ZodType<
  GetTransactionsByMonthRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionsByMonthRequest
> = z.object({
  budgetId: z.string(),
  month: z.string(),
  sinceDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  type: GetTransactionsByMonthType$outboundSchema.optional(),
  lastKnowledgeOfServer: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
    sinceDate: "since_date",
    lastKnowledgeOfServer: "last_knowledge_of_server",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionsByMonthRequest$ {
  /** @deprecated use `GetTransactionsByMonthRequest$inboundSchema` instead. */
  export const inboundSchema = GetTransactionsByMonthRequest$inboundSchema;
  /** @deprecated use `GetTransactionsByMonthRequest$outboundSchema` instead. */
  export const outboundSchema = GetTransactionsByMonthRequest$outboundSchema;
  /** @deprecated use `GetTransactionsByMonthRequest$Outbound` instead. */
  export type Outbound = GetTransactionsByMonthRequest$Outbound;
}

export function getTransactionsByMonthRequestToJSON(
  getTransactionsByMonthRequest: GetTransactionsByMonthRequest,
): string {
  return JSON.stringify(
    GetTransactionsByMonthRequest$outboundSchema.parse(
      getTransactionsByMonthRequest,
    ),
  );
}

export function getTransactionsByMonthRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTransactionsByMonthRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTransactionsByMonthRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTransactionsByMonthRequest' from JSON`,
  );
}
