/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ImportTransactionsRequest = {
  /**
   * The id of the budget. "last-used" can be used to specify the last used budget and "default" can be used if default budget selection is enabled (see: https://api.ynab.com/#oauth-default-budget).
   */
  budgetId: string;
};

/** @internal */
export type ImportTransactionsRequest$Outbound = {
  budget_id: string;
};

/** @internal */
export const ImportTransactionsRequest$outboundSchema: z.ZodType<
  ImportTransactionsRequest$Outbound,
  z.ZodTypeDef,
  ImportTransactionsRequest
> = z.object({
  budgetId: z.string(),
}).transform((v) => {
  return remap$(v, {
    budgetId: "budget_id",
  });
});

export function importTransactionsRequestToJSON(
  importTransactionsRequest: ImportTransactionsRequest,
): string {
  return JSON.stringify(
    ImportTransactionsRequest$outboundSchema.parse(importTransactionsRequest),
  );
}
