/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdatePayeeRequest = {
  /**
   * The id of the plan. "last-used" can be used to specify the last used plan and "default" can be used if default plan selection is enabled (see: https://api.ynab.com/#oauth-default-plan).
   */
  planId: string;
  /**
   * The id of the payee
   */
  payeeId: string;
  /**
   * The payee to update
   */
  patchPayeeWrapper: models.PatchPayeeWrapper;
};

/** @internal */
export type UpdatePayeeRequest$Outbound = {
  plan_id: string;
  payee_id: string;
  PatchPayeeWrapper: models.PatchPayeeWrapper$Outbound;
};

/** @internal */
export const UpdatePayeeRequest$outboundSchema: z.ZodType<
  UpdatePayeeRequest$Outbound,
  z.ZodTypeDef,
  UpdatePayeeRequest
> = z.object({
  planId: z.string(),
  payeeId: z.string(),
  patchPayeeWrapper: models.PatchPayeeWrapper$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    planId: "plan_id",
    payeeId: "payee_id",
    patchPayeeWrapper: "PatchPayeeWrapper",
  });
});

export function updatePayeeRequestToJSON(
  updatePayeeRequest: UpdatePayeeRequest,
): string {
  return JSON.stringify(
    UpdatePayeeRequest$outboundSchema.parse(updatePayeeRequest),
  );
}
