/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { AccountType, AccountType$inboundSchema } from "./accounttype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AccountBase = {
  id: string;
  name: string;
  /**
   * The type of account
   */
  type: AccountType;
  /**
   * Whether this account is "on budget" or not
   */
  onBudget: boolean;
  /**
   * Whether this account is closed or not
   */
  closed: boolean;
  note?: string | null | undefined;
  /**
   * The current available balance of the account in milliunits format
   */
  balance: number;
  /**
   * The current cleared balance of the account in milliunits format
   */
  clearedBalance: number;
  /**
   * The current uncleared balance of the account in milliunits format
   */
  unclearedBalance: number;
  /**
   * The payee id which should be used when transferring to this account
   */
  transferPayeeId: string | null;
  /**
   * Whether or not the account is linked to a financial institution for automatic transaction import.
   */
  directImportLinked?: boolean | undefined;
  /**
   * If an account linked to a financial institution (direct_import_linked=true) and the linked connection is not in a healthy state, this will be true.
   */
  directImportInError?: boolean | undefined;
  /**
   * A date/time specifying when the account was last reconciled.
   */
  lastReconciledAt?: Date | null | undefined;
  /**
   * This field is deprecated and will always be null.
   */
  debtOriginalBalance?: number | null | undefined;
  debtInterestRates?: { [k: string]: number } | null | undefined;
  debtMinimumPayments?: { [k: string]: number } | null | undefined;
  debtEscrowAmounts?: { [k: string]: number } | null | undefined;
  /**
   * Whether or not the account has been deleted.  Deleted accounts will only be included in delta requests.
   */
  deleted: boolean;
};

/** @internal */
export const AccountBase$inboundSchema: z.ZodType<
  AccountBase,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  type: AccountType$inboundSchema,
  on_budget: z.boolean(),
  closed: z.boolean(),
  note: z.nullable(z.string()).optional(),
  balance: z.number().int(),
  cleared_balance: z.number().int(),
  uncleared_balance: z.number().int(),
  transfer_payee_id: z.nullable(z.string()),
  direct_import_linked: z.boolean().optional(),
  direct_import_in_error: z.boolean().optional(),
  last_reconciled_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  debt_original_balance: z.nullable(z.number().int()).optional(),
  debt_interest_rates: z.nullable(z.record(z.number().int())).optional(),
  debt_minimum_payments: z.nullable(z.record(z.number().int())).optional(),
  debt_escrow_amounts: z.nullable(z.record(z.number().int())).optional(),
  deleted: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "on_budget": "onBudget",
    "cleared_balance": "clearedBalance",
    "uncleared_balance": "unclearedBalance",
    "transfer_payee_id": "transferPayeeId",
    "direct_import_linked": "directImportLinked",
    "direct_import_in_error": "directImportInError",
    "last_reconciled_at": "lastReconciledAt",
    "debt_original_balance": "debtOriginalBalance",
    "debt_interest_rates": "debtInterestRates",
    "debt_minimum_payments": "debtMinimumPayments",
    "debt_escrow_amounts": "debtEscrowAmounts",
  });
});

export function accountBaseFromJSON(
  jsonString: string,
): SafeParseResult<AccountBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountBase' from JSON`,
  );
}
