/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { BudgetDetail, BudgetDetail$inboundSchema } from "./budgetdetail.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BudgetDetailResponseData = {
  budget: BudgetDetail;
  /**
   * The knowledge of the server
   */
  serverKnowledge: number;
};

export type BudgetDetailResponse = {
  data: BudgetDetailResponseData;
};

/** @internal */
export const BudgetDetailResponseData$inboundSchema: z.ZodType<
  BudgetDetailResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget: BudgetDetail$inboundSchema,
  server_knowledge: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "server_knowledge": "serverKnowledge",
  });
});

export function budgetDetailResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<BudgetDetailResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BudgetDetailResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BudgetDetailResponseData' from JSON`,
  );
}

/** @internal */
export const BudgetDetailResponse$inboundSchema: z.ZodType<
  BudgetDetailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => BudgetDetailResponseData$inboundSchema),
});

export function budgetDetailResponseFromJSON(
  jsonString: string,
): SafeParseResult<BudgetDetailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BudgetDetailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BudgetDetailResponse' from JSON`,
  );
}
