/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { Account, Account$inboundSchema } from "./account.js";
import { Category, Category$inboundSchema } from "./category.js";
import { CategoryGroup, CategoryGroup$inboundSchema } from "./categorygroup.js";
import {
  CurrencyFormat,
  CurrencyFormat$inboundSchema,
} from "./currencyformat.js";
import { DateFormat, DateFormat$inboundSchema } from "./dateformat.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { MonthDetail, MonthDetail$inboundSchema } from "./monthdetail.js";
import { Payee, Payee$inboundSchema } from "./payee.js";
import { PayeeLocation, PayeeLocation$inboundSchema } from "./payeelocation.js";
import {
  ScheduledSubTransaction,
  ScheduledSubTransaction$inboundSchema,
} from "./scheduledsubtransaction.js";
import {
  ScheduledTransactionSummary,
  ScheduledTransactionSummary$inboundSchema,
} from "./scheduledtransactionsummary.js";
import {
  SubTransaction,
  SubTransaction$inboundSchema,
} from "./subtransaction.js";
import {
  TransactionSummary,
  TransactionSummary$inboundSchema,
} from "./transactionsummary.js";

export type BudgetDetail = {
  id: string;
  name: string;
  /**
   * The last time any changes were made to the budget from either a web or mobile client
   */
  lastModifiedOn?: Date | undefined;
  /**
   * The earliest budget month
   */
  firstMonth?: RFCDate | undefined;
  /**
   * The latest budget month
   */
  lastMonth?: RFCDate | undefined;
  /**
   * The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
   */
  dateFormat?: DateFormat | null | undefined;
  /**
   * The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
   */
  currencyFormat?: CurrencyFormat | null | undefined;
  accounts?: Array<Account> | undefined;
  payees?: Array<Payee> | undefined;
  payeeLocations?: Array<PayeeLocation> | undefined;
  categoryGroups?: Array<CategoryGroup> | undefined;
  categories?: Array<Category> | undefined;
  months?: Array<MonthDetail> | undefined;
  transactions?: Array<TransactionSummary> | undefined;
  subtransactions?: Array<SubTransaction> | undefined;
  scheduledTransactions?: Array<ScheduledTransactionSummary> | undefined;
  scheduledSubtransactions?: Array<ScheduledSubTransaction> | undefined;
};

/** @internal */
export const BudgetDetail$inboundSchema: z.ZodType<
  BudgetDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  last_modified_on: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  first_month: z.string().transform(v => new RFCDate(v)).optional(),
  last_month: z.string().transform(v => new RFCDate(v)).optional(),
  date_format: z.nullable(DateFormat$inboundSchema).optional(),
  currency_format: z.nullable(CurrencyFormat$inboundSchema).optional(),
  accounts: z.array(Account$inboundSchema).optional(),
  payees: z.array(Payee$inboundSchema).optional(),
  payee_locations: z.array(PayeeLocation$inboundSchema).optional(),
  category_groups: z.array(CategoryGroup$inboundSchema).optional(),
  categories: z.array(Category$inboundSchema).optional(),
  months: z.array(MonthDetail$inboundSchema).optional(),
  transactions: z.array(TransactionSummary$inboundSchema).optional(),
  subtransactions: z.array(SubTransaction$inboundSchema).optional(),
  scheduled_transactions: z.array(ScheduledTransactionSummary$inboundSchema)
    .optional(),
  scheduled_subtransactions: z.array(ScheduledSubTransaction$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "last_modified_on": "lastModifiedOn",
    "first_month": "firstMonth",
    "last_month": "lastMonth",
    "date_format": "dateFormat",
    "currency_format": "currencyFormat",
    "payee_locations": "payeeLocations",
    "category_groups": "categoryGroups",
    "scheduled_transactions": "scheduledTransactions",
    "scheduled_subtransactions": "scheduledSubtransactions",
  });
});

export function budgetDetailFromJSON(
  jsonString: string,
): SafeParseResult<BudgetDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BudgetDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BudgetDetail' from JSON`,
  );
}
