/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  BudgetSettings,
  BudgetSettings$inboundSchema,
} from "./budgetsettings.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BudgetSettingsResponseData = {
  settings: BudgetSettings;
};

export type BudgetSettingsResponse = {
  data: BudgetSettingsResponseData;
};

/** @internal */
export const BudgetSettingsResponseData$inboundSchema: z.ZodType<
  BudgetSettingsResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  settings: BudgetSettings$inboundSchema,
});

export function budgetSettingsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<BudgetSettingsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BudgetSettingsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BudgetSettingsResponseData' from JSON`,
  );
}

/** @internal */
export const BudgetSettingsResponse$inboundSchema: z.ZodType<
  BudgetSettingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => BudgetSettingsResponseData$inboundSchema),
});

export function budgetSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BudgetSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BudgetSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BudgetSettingsResponse' from JSON`,
  );
}
