/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CategoryGroup = {
  id: string;
  name: string;
  /**
   * Whether or not the category group is hidden
   */
  hidden: boolean;
  /**
   * Whether or not the category group has been deleted.  Deleted category groups will only be included in delta requests.
   */
  deleted: boolean;
};

/** @internal */
export const CategoryGroup$inboundSchema: z.ZodType<
  CategoryGroup,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  hidden: z.boolean(),
  deleted: z.boolean(),
});

export function categoryGroupFromJSON(
  jsonString: string,
): SafeParseResult<CategoryGroup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CategoryGroup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CategoryGroup' from JSON`,
  );
}
