/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The date format setting for the budget.  In some cases the format will not be available and will be specified as null.
 */
export type DateFormat = {
  format: string;
};

/** @internal */
export const DateFormat$inboundSchema: z.ZodType<
  DateFormat,
  z.ZodTypeDef,
  unknown
> = z.object({
  format: z.string(),
});

export function dateFormatFromJSON(
  jsonString: string,
): SafeParseResult<DateFormat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DateFormat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DateFormat' from JSON`,
  );
}
