/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { RFCDate } from "../types/rfcdate.js";

/**
 * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
 */
export const ExistingCategoryGoalFrequency = {
  Monthly: "monthly",
  Weekly: "weekly",
  Yearly: "yearly",
} as const;
/**
 * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
 */
export type ExistingCategoryGoalFrequency = ClosedEnum<
  typeof ExistingCategoryGoalFrequency
>;

export type ExistingCategory = {
  name?: string | null | undefined;
  note?: string | null | undefined;
  /**
   * The id of the category group to which this category belongs.  An internal category group may not be specified.
   */
  categoryGroupId?: string | undefined;
  /**
   * The goal target amount in milliunits format.  If value is specified and goal has not already been configured for category, a monthly goal will be created for the category with this target amount.  If goal_type is not specified, it will default to 'NEED' or 'MF' for Credit Card Payment categories. When updating a category, passing null removes any existing target.
   */
  goalTarget?: number | null | undefined;
  /**
   * The goal target date in ISO format (e.g. 2016-12-01).
   */
  goalTargetDate?: RFCDate | null | undefined;
  /**
   * Whether the goal requires the full target amount each period. Only supported for 'NEED' goals. When true, the goal is configured as 'Set aside another...'. When false, the goal is configured as 'Refill up to...'.
   */
  goalNeedsWholeAmount?: boolean | null | undefined;
  /**
   * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
   */
  goalFrequency?: ExistingCategoryGoalFrequency | undefined;
};

/** @internal */
export const ExistingCategoryGoalFrequency$outboundSchema: z.ZodNativeEnum<
  typeof ExistingCategoryGoalFrequency
> = z.nativeEnum(ExistingCategoryGoalFrequency);

/** @internal */
export type ExistingCategory$Outbound = {
  name?: string | null | undefined;
  note?: string | null | undefined;
  category_group_id?: string | undefined;
  goal_target?: number | null | undefined;
  goal_target_date?: string | null | undefined;
  goal_needs_whole_amount?: boolean | null | undefined;
  goal_frequency?: string | undefined;
};

/** @internal */
export const ExistingCategory$outboundSchema: z.ZodType<
  ExistingCategory$Outbound,
  z.ZodTypeDef,
  ExistingCategory
> = z.object({
  name: z.nullable(z.string()).optional(),
  note: z.nullable(z.string()).optional(),
  categoryGroupId: z.string().optional(),
  goalTarget: z.nullable(z.number().int()).optional(),
  goalTargetDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  goalNeedsWholeAmount: z.nullable(z.boolean()).optional(),
  goalFrequency: ExistingCategoryGoalFrequency$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    categoryGroupId: "category_group_id",
    goalTarget: "goal_target",
    goalTargetDate: "goal_target_date",
    goalNeedsWholeAmount: "goal_needs_whole_amount",
    goalFrequency: "goal_frequency",
  });
});

export function existingCategoryToJSON(
  existingCategory: ExistingCategory,
): string {
  return JSON.stringify(
    ExistingCategory$outboundSchema.parse(existingCategory),
  );
}
