/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  HybridTransaction,
  HybridTransaction$inboundSchema,
} from "./hybridtransaction.js";

export type HybridTransactionsResponseData = {
  transactions: Array<HybridTransaction>;
  /**
   * The knowledge of the server
   */
  serverKnowledge?: number | undefined;
};

export type HybridTransactionsResponse = {
  data: HybridTransactionsResponseData;
};

/** @internal */
export const HybridTransactionsResponseData$inboundSchema: z.ZodType<
  HybridTransactionsResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  transactions: z.array(HybridTransaction$inboundSchema),
  server_knowledge: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "server_knowledge": "serverKnowledge",
  });
});

export function hybridTransactionsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<HybridTransactionsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HybridTransactionsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HybridTransactionsResponseData' from JSON`,
  );
}

/** @internal */
export const HybridTransactionsResponse$inboundSchema: z.ZodType<
  HybridTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => HybridTransactionsResponseData$inboundSchema),
});

export function hybridTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<HybridTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HybridTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HybridTransactionsResponse' from JSON`,
  );
}
