/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { MonthSummary, MonthSummary$inboundSchema } from "./monthsummary.js";

export type MonthSummariesResponseData = {
  months: Array<MonthSummary>;
  /**
   * The knowledge of the server
   */
  serverKnowledge: number;
};

export type MonthSummariesResponse = {
  data: MonthSummariesResponseData;
};

/** @internal */
export const MonthSummariesResponseData$inboundSchema: z.ZodType<
  MonthSummariesResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  months: z.array(MonthSummary$inboundSchema),
  server_knowledge: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "server_knowledge": "serverKnowledge",
  });
});

export function monthSummariesResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<MonthSummariesResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonthSummariesResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonthSummariesResponseData' from JSON`,
  );
}

/** @internal */
export const MonthSummariesResponse$inboundSchema: z.ZodType<
  MonthSummariesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => MonthSummariesResponseData$inboundSchema),
});

export function monthSummariesResponseFromJSON(
  jsonString: string,
): SafeParseResult<MonthSummariesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonthSummariesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonthSummariesResponse' from JSON`,
  );
}
