/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import { RFCDate } from "../types/rfcdate.js";

/**
 * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
 */
export const NewCategoryGoalFrequency = {
  Monthly: "monthly",
  Weekly: "weekly",
  Yearly: "yearly",
} as const;
/**
 * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
 */
export type NewCategoryGoalFrequency = ClosedEnum<
  typeof NewCategoryGoalFrequency
>;

export type NewCategory = {
  name: string | null;
  note?: string | null | undefined;
  /**
   * The id of the category group to which this category belongs.  An internal category group may not be specified.
   */
  categoryGroupId: string;
  /**
   * The goal target amount in milliunits format.  If value is specified and goal has not already been configured for category, a monthly goal will be created for the category with this target amount.  If goal_type is not specified, it will default to 'NEED' or 'MF' for Credit Card Payment categories. When updating a category, passing null removes any existing target.
   */
  goalTarget?: number | null | undefined;
  /**
   * The goal target date in ISO format (e.g. 2016-12-01).
   */
  goalTargetDate?: RFCDate | null | undefined;
  /**
   * Whether the goal requires the full target amount each period. Only supported for 'NEED' goals. When true, the goal is configured as 'Set aside another...'. When false, the goal is configured as 'Refill up to...'.
   */
  goalNeedsWholeAmount?: boolean | null | undefined;
  /**
   * When specified, configures a recurring 'NEED' target of goal_target that repeats at this frequency, replacing any existing target. Requires goal_target. Cannot be combined with goal_target_date and is not supported for Credit Card Payment categories. Omit to leave an existing target's cadence unchanged.
   */
  goalFrequency?: NewCategoryGoalFrequency | undefined;
};

/** @internal */
export const NewCategoryGoalFrequency$outboundSchema: z.ZodNativeEnum<
  typeof NewCategoryGoalFrequency
> = z.nativeEnum(NewCategoryGoalFrequency);

/** @internal */
export type NewCategory$Outbound = {
  name: string | null;
  note?: string | null | undefined;
  category_group_id: string;
  goal_target?: number | null | undefined;
  goal_target_date?: string | null | undefined;
  goal_needs_whole_amount?: boolean | null | undefined;
  goal_frequency?: string | undefined;
};

/** @internal */
export const NewCategory$outboundSchema: z.ZodType<
  NewCategory$Outbound,
  z.ZodTypeDef,
  NewCategory
> = z.object({
  name: z.nullable(z.string()),
  note: z.nullable(z.string()).optional(),
  categoryGroupId: z.string(),
  goalTarget: z.nullable(z.number().int()).optional(),
  goalTargetDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  goalNeedsWholeAmount: z.nullable(z.boolean()).optional(),
  goalFrequency: NewCategoryGoalFrequency$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    categoryGroupId: "category_group_id",
    goalTarget: "goal_target",
    goalTargetDate: "goal_target_date",
    goalNeedsWholeAmount: "goal_needs_whole_amount",
    goalFrequency: "goal_frequency",
  });
});

export function newCategoryToJSON(newCategory: NewCategory): string {
  return JSON.stringify(NewCategory$outboundSchema.parse(newCategory));
}
