/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SaveCategoryGroup,
  SaveCategoryGroup$Outbound,
  SaveCategoryGroup$outboundSchema,
} from "./savecategorygroup.js";

export type PatchCategoryGroupWrapper = {
  categoryGroup: SaveCategoryGroup;
};

/** @internal */
export type PatchCategoryGroupWrapper$Outbound = {
  category_group: SaveCategoryGroup$Outbound;
};

/** @internal */
export const PatchCategoryGroupWrapper$outboundSchema: z.ZodType<
  PatchCategoryGroupWrapper$Outbound,
  z.ZodTypeDef,
  PatchCategoryGroupWrapper
> = z.object({
  categoryGroup: SaveCategoryGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    categoryGroup: "category_group",
  });
});

export function patchCategoryGroupWrapperToJSON(
  patchCategoryGroupWrapper: PatchCategoryGroupWrapper,
): string {
  return JSON.stringify(
    PatchCategoryGroupWrapper$outboundSchema.parse(patchCategoryGroupWrapper),
  );
}
