/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Payee, Payee$inboundSchema } from "./payee.js";

export type PayeesResponseData = {
  payees: Array<Payee>;
  /**
   * The knowledge of the server
   */
  serverKnowledge: number;
};

export type PayeesResponse = {
  data: PayeesResponseData;
};

/** @internal */
export const PayeesResponseData$inboundSchema: z.ZodType<
  PayeesResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  payees: z.array(Payee$inboundSchema),
  server_knowledge: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "server_knowledge": "serverKnowledge",
  });
});

export function payeesResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PayeesResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeesResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeesResponseData' from JSON`,
  );
}

/** @internal */
export const PayeesResponse$inboundSchema: z.ZodType<
  PayeesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PayeesResponseData$inboundSchema),
});

export function payeesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayeesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeesResponse' from JSON`,
  );
}
