/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Payee, Payee$inboundSchema } from "./payee.js";

export type PayeeResponseData = {
  payee: Payee;
};

export type PayeeResponse = {
  data: PayeeResponseData;
};

/** @internal */
export const PayeeResponseData$inboundSchema: z.ZodType<
  PayeeResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  payee: Payee$inboundSchema,
});

export function payeeResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PayeeResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeeResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeeResponseData' from JSON`,
  );
}

/** @internal */
export const PayeeResponse$inboundSchema: z.ZodType<
  PayeeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PayeeResponseData$inboundSchema),
});

export function payeeResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayeeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeeResponse' from JSON`,
  );
}
