/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PayeeLocation, PayeeLocation$inboundSchema } from "./payeelocation.js";

export type PayeeLocationResponseData = {
  payeeLocation: PayeeLocation;
};

export type PayeeLocationResponse = {
  data: PayeeLocationResponseData;
};

/** @internal */
export const PayeeLocationResponseData$inboundSchema: z.ZodType<
  PayeeLocationResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  payee_location: PayeeLocation$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "payee_location": "payeeLocation",
  });
});

export function payeeLocationResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PayeeLocationResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeeLocationResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeeLocationResponseData' from JSON`,
  );
}

/** @internal */
export const PayeeLocationResponse$inboundSchema: z.ZodType<
  PayeeLocationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PayeeLocationResponseData$inboundSchema),
});

export function payeeLocationResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayeeLocationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeeLocationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeeLocationResponse' from JSON`,
  );
}
