/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PayeeLocation = {
  id: string;
  payeeId: string;
  latitude: string;
  longitude: string;
  /**
   * Whether or not the payee location has been deleted.  Deleted payee locations will only be included in delta requests.
   */
  deleted: boolean;
};

/** @internal */
export const PayeeLocation$inboundSchema: z.ZodType<
  PayeeLocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  payee_id: z.string(),
  latitude: z.string(),
  longitude: z.string(),
  deleted: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "payee_id": "payeeId",
  });
});

export function payeeLocationFromJSON(
  jsonString: string,
): SafeParseResult<PayeeLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayeeLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayeeLocation' from JSON`,
  );
}
