/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { Account, Account$inboundSchema } from "./account.js";
import {
  CurrencyFormat,
  CurrencyFormat$inboundSchema,
} from "./currencyformat.js";
import { DateFormat, DateFormat$inboundSchema } from "./dateformat.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PlanSummary = {
  id: string;
  name: string;
  /**
   * The last time any changes were made to the plan from either a web or mobile client
   */
  lastModifiedOn?: Date | undefined;
  /**
   * The earliest plan month
   */
  firstMonth?: RFCDate | undefined;
  /**
   * The latest plan month
   */
  lastMonth?: RFCDate | undefined;
  /**
   * The date format setting for the plan.  In some cases the format will not be available and will be specified as null.
   */
  dateFormat?: DateFormat | null | undefined;
  /**
   * The currency format setting for the plan.  In some cases the format will not be available and will be specified as null.
   */
  currencyFormat?: CurrencyFormat | null | undefined;
  /**
   * The plan accounts (only included if `include_accounts=true` specified as query parameter)
   */
  accounts?: Array<Account> | undefined;
};

/** @internal */
export const PlanSummary$inboundSchema: z.ZodType<
  PlanSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  last_modified_on: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  first_month: z.string().transform(v => new RFCDate(v)).optional(),
  last_month: z.string().transform(v => new RFCDate(v)).optional(),
  date_format: z.nullable(DateFormat$inboundSchema).optional(),
  currency_format: z.nullable(CurrencyFormat$inboundSchema).optional(),
  accounts: z.array(Account$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "last_modified_on": "lastModifiedOn",
    "first_month": "firstMonth",
    "last_month": "lastMonth",
    "date_format": "dateFormat",
    "currency_format": "currencyFormat",
  });
});

export function planSummaryFromJSON(
  jsonString: string,
): SafeParseResult<PlanSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanSummary' from JSON`,
  );
}
