/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { Account, Account$inboundSchema } from "./account.js";
import {
  CurrencyFormat,
  CurrencyFormat$inboundSchema,
} from "./currencyformat.js";
import { DateFormat, DateFormat$inboundSchema } from "./dateformat.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { PlanSummary, PlanSummary$inboundSchema } from "./plansummary.js";

export type DefaultPlan = {
  id: string;
  name: string;
  /**
   * The last time any changes were made to the plan from either a web or mobile client
   */
  lastModifiedOn?: Date | undefined;
  /**
   * The earliest plan month
   */
  firstMonth?: RFCDate | undefined;
  /**
   * The latest plan month
   */
  lastMonth?: RFCDate | undefined;
  /**
   * The date format setting for the plan.  In some cases the format will not be available and will be specified as null.
   */
  dateFormat?: DateFormat | null | undefined;
  /**
   * The currency format setting for the plan.  In some cases the format will not be available and will be specified as null.
   */
  currencyFormat?: CurrencyFormat | null | undefined;
  /**
   * The plan accounts (only included if `include_accounts=true` specified as query parameter)
   */
  accounts?: Array<Account> | undefined;
};

export type PlanSummaryResponseData = {
  plans: Array<PlanSummary>;
  defaultPlan?: DefaultPlan | null | undefined;
};

export type PlanSummaryResponse = {
  data: PlanSummaryResponseData;
};

/** @internal */
export const DefaultPlan$inboundSchema: z.ZodType<
  DefaultPlan,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  last_modified_on: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  first_month: z.string().transform(v => new RFCDate(v)).optional(),
  last_month: z.string().transform(v => new RFCDate(v)).optional(),
  date_format: z.nullable(DateFormat$inboundSchema).optional(),
  currency_format: z.nullable(CurrencyFormat$inboundSchema).optional(),
  accounts: z.array(Account$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "last_modified_on": "lastModifiedOn",
    "first_month": "firstMonth",
    "last_month": "lastMonth",
    "date_format": "dateFormat",
    "currency_format": "currencyFormat",
  });
});

export function defaultPlanFromJSON(
  jsonString: string,
): SafeParseResult<DefaultPlan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DefaultPlan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DefaultPlan' from JSON`,
  );
}

/** @internal */
export const PlanSummaryResponseData$inboundSchema: z.ZodType<
  PlanSummaryResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  plans: z.array(PlanSummary$inboundSchema),
  default_plan: z.nullable(z.lazy(() => DefaultPlan$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "default_plan": "defaultPlan",
  });
});

export function planSummaryResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PlanSummaryResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanSummaryResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanSummaryResponseData' from JSON`,
  );
}

/** @internal */
export const PlanSummaryResponse$inboundSchema: z.ZodType<
  PlanSummaryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PlanSummaryResponseData$inboundSchema),
});

export function planSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlanSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanSummaryResponse' from JSON`,
  );
}
