/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  SaveAccount,
  SaveAccount$Outbound,
  SaveAccount$outboundSchema,
} from "./saveaccount.js";

export type PostAccountWrapper = {
  account: SaveAccount;
};

/** @internal */
export type PostAccountWrapper$Outbound = {
  account: SaveAccount$Outbound;
};

/** @internal */
export const PostAccountWrapper$outboundSchema: z.ZodType<
  PostAccountWrapper$Outbound,
  z.ZodTypeDef,
  PostAccountWrapper
> = z.object({
  account: SaveAccount$outboundSchema,
});

export function postAccountWrapperToJSON(
  postAccountWrapper: PostAccountWrapper,
): string {
  return JSON.stringify(
    PostAccountWrapper$outboundSchema.parse(postAccountWrapper),
  );
}
