/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  NewCategory,
  NewCategory$Outbound,
  NewCategory$outboundSchema,
} from "./newcategory.js";

export type PostCategoryWrapper = {
  category: NewCategory;
};

/** @internal */
export type PostCategoryWrapper$Outbound = {
  category: NewCategory$Outbound;
};

/** @internal */
export const PostCategoryWrapper$outboundSchema: z.ZodType<
  PostCategoryWrapper$Outbound,
  z.ZodTypeDef,
  PostCategoryWrapper
> = z.object({
  category: NewCategory$outboundSchema,
});

export function postCategoryWrapperToJSON(
  postCategoryWrapper: PostCategoryWrapper,
): string {
  return JSON.stringify(
    PostCategoryWrapper$outboundSchema.parse(postCategoryWrapper),
  );
}
