/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  NewTransaction,
  NewTransaction$Outbound,
  NewTransaction$outboundSchema,
} from "./newtransaction.js";

export type PostTransactionsWrapper = {
  transaction?: NewTransaction | undefined;
  transactions?: Array<NewTransaction> | undefined;
};

/** @internal */
export type PostTransactionsWrapper$Outbound = {
  transaction?: NewTransaction$Outbound | undefined;
  transactions?: Array<NewTransaction$Outbound> | undefined;
};

/** @internal */
export const PostTransactionsWrapper$outboundSchema: z.ZodType<
  PostTransactionsWrapper$Outbound,
  z.ZodTypeDef,
  PostTransactionsWrapper
> = z.object({
  transaction: NewTransaction$outboundSchema.optional(),
  transactions: z.array(NewTransaction$outboundSchema).optional(),
});

export function postTransactionsWrapperToJSON(
  postTransactionsWrapper: PostTransactionsWrapper,
): string {
  return JSON.stringify(
    PostTransactionsWrapper$outboundSchema.parse(postTransactionsWrapper),
  );
}
