/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SaveCategoryGroup,
  SaveCategoryGroup$Outbound,
  SaveCategoryGroup$outboundSchema,
} from "./savecategorygroup.js";

export type PostCategoryGroupWrapper = {
  categoryGroup: SaveCategoryGroup;
};

/** @internal */
export type PostCategoryGroupWrapper$Outbound = {
  category_group: SaveCategoryGroup$Outbound;
};

/** @internal */
export const PostCategoryGroupWrapper$outboundSchema: z.ZodType<
  PostCategoryGroupWrapper$Outbound,
  z.ZodTypeDef,
  PostCategoryGroupWrapper
> = z.object({
  categoryGroup: SaveCategoryGroup$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    categoryGroup: "category_group",
  });
});

export function postCategoryGroupWrapperToJSON(
  postCategoryGroupWrapper: PostCategoryGroupWrapper,
): string {
  return JSON.stringify(
    PostCategoryGroupWrapper$outboundSchema.parse(postCategoryGroupWrapper),
  );
}
