/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  PostPayee,
  PostPayee$Outbound,
  PostPayee$outboundSchema,
} from "./postpayee.js";

export type PostPayeeWrapper = {
  payee: PostPayee;
};

/** @internal */
export type PostPayeeWrapper$Outbound = {
  payee: PostPayee$Outbound;
};

/** @internal */
export const PostPayeeWrapper$outboundSchema: z.ZodType<
  PostPayeeWrapper$Outbound,
  z.ZodTypeDef,
  PostPayeeWrapper
> = z.object({
  payee: PostPayee$outboundSchema,
});

export function postPayeeWrapperToJSON(
  postPayeeWrapper: PostPayeeWrapper,
): string {
  return JSON.stringify(
    PostPayeeWrapper$outboundSchema.parse(postPayeeWrapper),
  );
}
