/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostPayee = {
  /**
   * The name of the payee.
   */
  name: string;
};

/** @internal */
export type PostPayee$Outbound = {
  name: string;
};

/** @internal */
export const PostPayee$outboundSchema: z.ZodType<
  PostPayee$Outbound,
  z.ZodTypeDef,
  PostPayee
> = z.object({
  name: z.string(),
});

export function postPayeeToJSON(postPayee: PostPayee): string {
  return JSON.stringify(PostPayee$outboundSchema.parse(postPayee));
}
