/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ExistingTransaction,
  ExistingTransaction$Outbound,
  ExistingTransaction$outboundSchema,
} from "./existingtransaction.js";

export type PutTransactionWrapper = {
  transaction: ExistingTransaction;
};

/** @internal */
export type PutTransactionWrapper$Outbound = {
  transaction: ExistingTransaction$Outbound;
};

/** @internal */
export const PutTransactionWrapper$outboundSchema: z.ZodType<
  PutTransactionWrapper$Outbound,
  z.ZodTypeDef,
  PutTransactionWrapper
> = z.object({
  transaction: ExistingTransaction$outboundSchema,
});

export function putTransactionWrapperToJSON(
  putTransactionWrapper: PutTransactionWrapper,
): string {
  return JSON.stringify(
    PutTransactionWrapper$outboundSchema.parse(putTransactionWrapper),
  );
}
