/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SaveCategoryGroup = {
  /**
   * The name of the category group. The name must be a maximum of 50 characters.
   */
  name: string;
};

/** @internal */
export type SaveCategoryGroup$Outbound = {
  name: string;
};

/** @internal */
export const SaveCategoryGroup$outboundSchema: z.ZodType<
  SaveCategoryGroup$Outbound,
  z.ZodTypeDef,
  SaveCategoryGroup
> = z.object({
  name: z.string(),
});

export function saveCategoryGroupToJSON(
  saveCategoryGroup: SaveCategoryGroup,
): string {
  return JSON.stringify(
    SaveCategoryGroup$outboundSchema.parse(saveCategoryGroup),
  );
}
