/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The type of account to create or update
 */
export const SaveAccountType = {
  Checking: "checking",
  Savings: "savings",
  Cash: "cash",
  CreditCard: "creditCard",
  OtherAsset: "otherAsset",
  OtherLiability: "otherLiability",
} as const;
/**
 * The type of account to create or update
 */
export type SaveAccountType = ClosedEnum<typeof SaveAccountType>;

/** @internal */
export const SaveAccountType$outboundSchema: z.ZodNativeEnum<
  typeof SaveAccountType
> = z.nativeEnum(SaveAccountType);
