/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ScheduledTransactionDetail,
  ScheduledTransactionDetail$inboundSchema,
} from "./scheduledtransactiondetail.js";

export type ScheduledTransactionsResponseData = {
  scheduledTransactions: Array<ScheduledTransactionDetail>;
  /**
   * The knowledge of the server
   */
  serverKnowledge: number;
};

export type ScheduledTransactionsResponse = {
  data: ScheduledTransactionsResponseData;
};

/** @internal */
export const ScheduledTransactionsResponseData$inboundSchema: z.ZodType<
  ScheduledTransactionsResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduled_transactions: z.array(ScheduledTransactionDetail$inboundSchema),
  server_knowledge: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "scheduled_transactions": "scheduledTransactions",
    "server_knowledge": "serverKnowledge",
  });
});

export function scheduledTransactionsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledTransactionsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledTransactionsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledTransactionsResponseData' from JSON`,
  );
}

/** @internal */
export const ScheduledTransactionsResponse$inboundSchema: z.ZodType<
  ScheduledTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ScheduledTransactionsResponseData$inboundSchema),
});

export function scheduledTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledTransactionsResponse' from JSON`,
  );
}
