/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { RFCDate } from "../types/rfcdate.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransactionFlagColor,
  TransactionFlagColor$inboundSchema,
} from "./transactionflagcolor.js";

export const ScheduledTransactionSummaryBaseFrequency = {
  Never: "never",
  Daily: "daily",
  Weekly: "weekly",
  EveryOtherWeek: "everyOtherWeek",
  TwiceAMonth: "twiceAMonth",
  Every4Weeks: "every4Weeks",
  Monthly: "monthly",
  EveryOtherMonth: "everyOtherMonth",
  Every3Months: "every3Months",
  Every4Months: "every4Months",
  TwiceAYear: "twiceAYear",
  Yearly: "yearly",
  EveryOtherYear: "everyOtherYear",
} as const;
export type ScheduledTransactionSummaryBaseFrequency = ClosedEnum<
  typeof ScheduledTransactionSummaryBaseFrequency
>;

export type ScheduledTransactionSummaryBase = {
  id: string;
  /**
   * The first date for which the Scheduled Transaction was scheduled.
   */
  dateFirst: RFCDate;
  /**
   * The next date for which the Scheduled Transaction is scheduled.
   */
  dateNext: RFCDate;
  frequency: ScheduledTransactionSummaryBaseFrequency;
  /**
   * The scheduled transaction amount in milliunits format
   */
  amount: number;
  memo?: string | null | undefined;
  /**
   * The transaction flag
   */
  flagColor?: TransactionFlagColor | null | undefined;
  /**
   * The customized name of a transaction flag
   */
  flagName?: string | null | undefined;
  accountId: string;
  payeeId?: string | null | undefined;
  categoryId?: string | null | undefined;
  /**
   * If a transfer, the account_id which the scheduled transaction transfers to
   */
  transferAccountId?: string | null | undefined;
  /**
   * Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
   */
  deleted: boolean;
};

/** @internal */
export const ScheduledTransactionSummaryBaseFrequency$inboundSchema:
  z.ZodNativeEnum<typeof ScheduledTransactionSummaryBaseFrequency> = z
    .nativeEnum(ScheduledTransactionSummaryBaseFrequency);

/** @internal */
export const ScheduledTransactionSummaryBase$inboundSchema: z.ZodType<
  ScheduledTransactionSummaryBase,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  date_first: z.string().transform(v => new RFCDate(v)),
  date_next: z.string().transform(v => new RFCDate(v)),
  frequency: ScheduledTransactionSummaryBaseFrequency$inboundSchema,
  amount: z.number().int(),
  memo: z.nullable(z.string()).optional(),
  flag_color: z.nullable(TransactionFlagColor$inboundSchema).optional(),
  flag_name: z.nullable(z.string()).optional(),
  account_id: z.string(),
  payee_id: z.nullable(z.string()).optional(),
  category_id: z.nullable(z.string()).optional(),
  transfer_account_id: z.nullable(z.string()).optional(),
  deleted: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "date_first": "dateFirst",
    "date_next": "dateNext",
    "flag_color": "flagColor",
    "flag_name": "flagName",
    "account_id": "accountId",
    "payee_id": "payeeId",
    "category_id": "categoryId",
    "transfer_account_id": "transferAccountId",
  });
});

export function scheduledTransactionSummaryBaseFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledTransactionSummaryBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledTransactionSummaryBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledTransactionSummaryBase' from JSON`,
  );
}
