/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ScheduledTransactionDetail,
  ScheduledTransactionDetail$inboundSchema,
} from "./scheduledtransactiondetail.js";

export type ScheduledTransactionResponseData = {
  scheduledTransaction: ScheduledTransactionDetail;
};

export type ScheduledTransactionResponse = {
  data: ScheduledTransactionResponseData;
};

/** @internal */
export const ScheduledTransactionResponseData$inboundSchema: z.ZodType<
  ScheduledTransactionResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  scheduled_transaction: ScheduledTransactionDetail$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "scheduled_transaction": "scheduledTransaction",
  });
});

export function scheduledTransactionResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledTransactionResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledTransactionResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledTransactionResponseData' from JSON`,
  );
}

/** @internal */
export const ScheduledTransactionResponse$inboundSchema: z.ZodType<
  ScheduledTransactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ScheduledTransactionResponseData$inboundSchema),
});

export function scheduledTransactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScheduledTransactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScheduledTransactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScheduledTransactionResponse' from JSON`,
  );
}
