/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransactionDetail,
  TransactionDetail$inboundSchema,
} from "./transactiondetail.js";

export type TransactionsResponseData = {
  transactions: Array<TransactionDetail>;
  /**
   * The knowledge of the server
   */
  serverKnowledge: number;
};

export type TransactionsResponse = {
  data: TransactionsResponseData;
};

/** @internal */
export const TransactionsResponseData$inboundSchema: z.ZodType<
  TransactionsResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  transactions: z.array(TransactionDetail$inboundSchema),
  server_knowledge: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "server_knowledge": "serverKnowledge",
  });
});

export function transactionsResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<TransactionsResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionsResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionsResponseData' from JSON`,
  );
}

/** @internal */
export const TransactionsResponse$inboundSchema: z.ZodType<
  TransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => TransactionsResponseData$inboundSchema),
});

export function transactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionsResponse' from JSON`,
  );
}
