/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * The cleared status of the transaction
 */
export const TransactionClearedStatus = {
  Cleared: "cleared",
  Uncleared: "uncleared",
  Reconciled: "reconciled",
} as const;
/**
 * The cleared status of the transaction
 */
export type TransactionClearedStatus = ClosedEnum<
  typeof TransactionClearedStatus
>;

/** @internal */
export const TransactionClearedStatus$inboundSchema: z.ZodNativeEnum<
  typeof TransactionClearedStatus
> = z.nativeEnum(TransactionClearedStatus);
/** @internal */
export const TransactionClearedStatus$outboundSchema: z.ZodNativeEnum<
  typeof TransactionClearedStatus
> = TransactionClearedStatus$inboundSchema;
