/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { User, User$inboundSchema } from "./user.js";

export type UserResponseData = {
  user: User;
};

export type UserResponse = {
  data: UserResponseData;
};

/** @internal */
export const UserResponseData$inboundSchema: z.ZodType<
  UserResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  user: User$inboundSchema,
});

export function userResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<UserResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserResponseData' from JSON`,
  );
}

/** @internal */
export const UserResponse$inboundSchema: z.ZodType<
  UserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => UserResponseData$inboundSchema),
});

export function userResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserResponse' from JSON`,
  );
}
